package com.atlsmall.entity;

public class CommCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NO
     *
     * @mbggenerated
     */
    private Integer ccNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CG_NO
     *
     * @mbggenerated
     */
    private Integer cgNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_CODE
     *
     * @mbggenerated
     */
    private String ccCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_KR
     *
     * @mbggenerated
     */
    private String ccNameKr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_US
     *
     * @mbggenerated
     */
    private String ccNameUs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_CN
     *
     * @mbggenerated
     */
    private String ccNameCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_JP
     *
     * @mbggenerated
     */
    private String ccNameJp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_ID
     *
     * @mbggenerated
     */
    private String ccNameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_FR
     *
     * @mbggenerated
     */
    private String ccNameFr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_ES
     *
     * @mbggenerated
     */
    private String ccNameEs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_RU
     *
     * @mbggenerated
     */
    private String ccNameRu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_DE
     *
     * @mbggenerated
     */
    private String ccNameDe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_NAME_AU
     *
     * @mbggenerated
     */
    private String ccNameAu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_SORT
     *
     * @mbggenerated
     */
    private Integer ccSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_USE
     *
     * @mbggenerated
     */
    private String ccUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_ETC
     *
     * @mbggenerated
     */
    private String ccEtc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_IMG1
     *
     * @mbggenerated
     */
    private String ccImg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMM_CODE.CC_IMG2
     *
     * @mbggenerated
     */
    private String ccImg2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NO
     *
     * @return the value of COMM_CODE.CC_NO
     *
     * @mbggenerated
     */
    public Integer getCcNo() {
        return ccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NO
     *
     * @param ccNo the value for COMM_CODE.CC_NO
     *
     * @mbggenerated
     */
    public void setCcNo(Integer ccNo) {
        this.ccNo = ccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CG_NO
     *
     * @return the value of COMM_CODE.CG_NO
     *
     * @mbggenerated
     */
    public Integer getCgNo() {
        return cgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CG_NO
     *
     * @param cgNo the value for COMM_CODE.CG_NO
     *
     * @mbggenerated
     */
    public void setCgNo(Integer cgNo) {
        this.cgNo = cgNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_CODE
     *
     * @return the value of COMM_CODE.CC_CODE
     *
     * @mbggenerated
     */
    public String getCcCode() {
        return ccCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_CODE
     *
     * @param ccCode the value for COMM_CODE.CC_CODE
     *
     * @mbggenerated
     */
    public void setCcCode(String ccCode) {
        this.ccCode = ccCode == null ? null : ccCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_KR
     *
     * @return the value of COMM_CODE.CC_NAME_KR
     *
     * @mbggenerated
     */
    public String getCcNameKr() {
        return ccNameKr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_KR
     *
     * @param ccNameKr the value for COMM_CODE.CC_NAME_KR
     *
     * @mbggenerated
     */
    public void setCcNameKr(String ccNameKr) {
        this.ccNameKr = ccNameKr == null ? null : ccNameKr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_US
     *
     * @return the value of COMM_CODE.CC_NAME_US
     *
     * @mbggenerated
     */
    public String getCcNameUs() {
        return ccNameUs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_US
     *
     * @param ccNameUs the value for COMM_CODE.CC_NAME_US
     *
     * @mbggenerated
     */
    public void setCcNameUs(String ccNameUs) {
        this.ccNameUs = ccNameUs == null ? null : ccNameUs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_CN
     *
     * @return the value of COMM_CODE.CC_NAME_CN
     *
     * @mbggenerated
     */
    public String getCcNameCn() {
        return ccNameCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_CN
     *
     * @param ccNameCn the value for COMM_CODE.CC_NAME_CN
     *
     * @mbggenerated
     */
    public void setCcNameCn(String ccNameCn) {
        this.ccNameCn = ccNameCn == null ? null : ccNameCn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_JP
     *
     * @return the value of COMM_CODE.CC_NAME_JP
     *
     * @mbggenerated
     */
    public String getCcNameJp() {
        return ccNameJp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_JP
     *
     * @param ccNameJp the value for COMM_CODE.CC_NAME_JP
     *
     * @mbggenerated
     */
    public void setCcNameJp(String ccNameJp) {
        this.ccNameJp = ccNameJp == null ? null : ccNameJp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_ID
     *
     * @return the value of COMM_CODE.CC_NAME_ID
     *
     * @mbggenerated
     */
    public String getCcNameId() {
        return ccNameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_ID
     *
     * @param ccNameId the value for COMM_CODE.CC_NAME_ID
     *
     * @mbggenerated
     */
    public void setCcNameId(String ccNameId) {
        this.ccNameId = ccNameId == null ? null : ccNameId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_FR
     *
     * @return the value of COMM_CODE.CC_NAME_FR
     *
     * @mbggenerated
     */
    public String getCcNameFr() {
        return ccNameFr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_FR
     *
     * @param ccNameFr the value for COMM_CODE.CC_NAME_FR
     *
     * @mbggenerated
     */
    public void setCcNameFr(String ccNameFr) {
        this.ccNameFr = ccNameFr == null ? null : ccNameFr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_ES
     *
     * @return the value of COMM_CODE.CC_NAME_ES
     *
     * @mbggenerated
     */
    public String getCcNameEs() {
        return ccNameEs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_ES
     *
     * @param ccNameEs the value for COMM_CODE.CC_NAME_ES
     *
     * @mbggenerated
     */
    public void setCcNameEs(String ccNameEs) {
        this.ccNameEs = ccNameEs == null ? null : ccNameEs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_RU
     *
     * @return the value of COMM_CODE.CC_NAME_RU
     *
     * @mbggenerated
     */
    public String getCcNameRu() {
        return ccNameRu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_RU
     *
     * @param ccNameRu the value for COMM_CODE.CC_NAME_RU
     *
     * @mbggenerated
     */
    public void setCcNameRu(String ccNameRu) {
        this.ccNameRu = ccNameRu == null ? null : ccNameRu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_DE
     *
     * @return the value of COMM_CODE.CC_NAME_DE
     *
     * @mbggenerated
     */
    public String getCcNameDe() {
        return ccNameDe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_DE
     *
     * @param ccNameDe the value for COMM_CODE.CC_NAME_DE
     *
     * @mbggenerated
     */
    public void setCcNameDe(String ccNameDe) {
        this.ccNameDe = ccNameDe == null ? null : ccNameDe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_NAME_AU
     *
     * @return the value of COMM_CODE.CC_NAME_AU
     *
     * @mbggenerated
     */
    public String getCcNameAu() {
        return ccNameAu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_NAME_AU
     *
     * @param ccNameAu the value for COMM_CODE.CC_NAME_AU
     *
     * @mbggenerated
     */
    public void setCcNameAu(String ccNameAu) {
        this.ccNameAu = ccNameAu == null ? null : ccNameAu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_SORT
     *
     * @return the value of COMM_CODE.CC_SORT
     *
     * @mbggenerated
     */
    public Integer getCcSort() {
        return ccSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_SORT
     *
     * @param ccSort the value for COMM_CODE.CC_SORT
     *
     * @mbggenerated
     */
    public void setCcSort(Integer ccSort) {
        this.ccSort = ccSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_USE
     *
     * @return the value of COMM_CODE.CC_USE
     *
     * @mbggenerated
     */
    public String getCcUse() {
        return ccUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_USE
     *
     * @param ccUse the value for COMM_CODE.CC_USE
     *
     * @mbggenerated
     */
    public void setCcUse(String ccUse) {
        this.ccUse = ccUse == null ? null : ccUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_ETC
     *
     * @return the value of COMM_CODE.CC_ETC
     *
     * @mbggenerated
     */
    public String getCcEtc() {
        return ccEtc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_ETC
     *
     * @param ccEtc the value for COMM_CODE.CC_ETC
     *
     * @mbggenerated
     */
    public void setCcEtc(String ccEtc) {
        this.ccEtc = ccEtc == null ? null : ccEtc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_IMG1
     *
     * @return the value of COMM_CODE.CC_IMG1
     *
     * @mbggenerated
     */
    public String getCcImg1() {
        return ccImg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_IMG1
     *
     * @param ccImg1 the value for COMM_CODE.CC_IMG1
     *
     * @mbggenerated
     */
    public void setCcImg1(String ccImg1) {
        this.ccImg1 = ccImg1 == null ? null : ccImg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMM_CODE.CC_IMG2
     *
     * @return the value of COMM_CODE.CC_IMG2
     *
     * @mbggenerated
     */
    public String getCcImg2() {
        return ccImg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMM_CODE.CC_IMG2
     *
     * @param ccImg2 the value for COMM_CODE.CC_IMG2
     *
     * @mbggenerated
     */
    public void setCcImg2(String ccImg2) {
        this.ccImg2 = ccImg2 == null ? null : ccImg2.trim();
    }
}