package com.atlsmall.entity;

import java.util.ArrayList;
import java.util.List;

public class CommCodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public CommCodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCcNoIsNull() {
            addCriterion("CC_NO is null");
            return (Criteria) this;
        }

        public Criteria andCcNoIsNotNull() {
            addCriterion("CC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCcNoEqualTo(Integer value) {
            addCriterion("CC_NO =", value, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoNotEqualTo(Integer value) {
            addCriterion("CC_NO <>", value, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoGreaterThan(Integer value) {
            addCriterion("CC_NO >", value, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("CC_NO >=", value, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoLessThan(Integer value) {
            addCriterion("CC_NO <", value, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoLessThanOrEqualTo(Integer value) {
            addCriterion("CC_NO <=", value, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoIn(List<Integer> values) {
            addCriterion("CC_NO in", values, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoNotIn(List<Integer> values) {
            addCriterion("CC_NO not in", values, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoBetween(Integer value1, Integer value2) {
            addCriterion("CC_NO between", value1, value2, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCcNoNotBetween(Integer value1, Integer value2) {
            addCriterion("CC_NO not between", value1, value2, "ccNo");
            return (Criteria) this;
        }

        public Criteria andCgNoIsNull() {
            addCriterion("CG_NO is null");
            return (Criteria) this;
        }

        public Criteria andCgNoIsNotNull() {
            addCriterion("CG_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCgNoEqualTo(Integer value) {
            addCriterion("CG_NO =", value, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoNotEqualTo(Integer value) {
            addCriterion("CG_NO <>", value, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoGreaterThan(Integer value) {
            addCriterion("CG_NO >", value, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("CG_NO >=", value, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoLessThan(Integer value) {
            addCriterion("CG_NO <", value, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoLessThanOrEqualTo(Integer value) {
            addCriterion("CG_NO <=", value, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoIn(List<Integer> values) {
            addCriterion("CG_NO in", values, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoNotIn(List<Integer> values) {
            addCriterion("CG_NO not in", values, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoBetween(Integer value1, Integer value2) {
            addCriterion("CG_NO between", value1, value2, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCgNoNotBetween(Integer value1, Integer value2) {
            addCriterion("CG_NO not between", value1, value2, "cgNo");
            return (Criteria) this;
        }

        public Criteria andCcCodeIsNull() {
            addCriterion("CC_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCcCodeIsNotNull() {
            addCriterion("CC_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCcCodeEqualTo(String value) {
            addCriterion("CC_CODE =", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeNotEqualTo(String value) {
            addCriterion("CC_CODE <>", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeGreaterThan(String value) {
            addCriterion("CC_CODE >", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CC_CODE >=", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeLessThan(String value) {
            addCriterion("CC_CODE <", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeLessThanOrEqualTo(String value) {
            addCriterion("CC_CODE <=", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeLike(String value) {
            addCriterion("CC_CODE like", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeNotLike(String value) {
            addCriterion("CC_CODE not like", value, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeIn(List<String> values) {
            addCriterion("CC_CODE in", values, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeNotIn(List<String> values) {
            addCriterion("CC_CODE not in", values, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeBetween(String value1, String value2) {
            addCriterion("CC_CODE between", value1, value2, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcCodeNotBetween(String value1, String value2) {
            addCriterion("CC_CODE not between", value1, value2, "ccCode");
            return (Criteria) this;
        }

        public Criteria andCcNameKrIsNull() {
            addCriterion("CC_NAME_KR is null");
            return (Criteria) this;
        }

        public Criteria andCcNameKrIsNotNull() {
            addCriterion("CC_NAME_KR is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameKrEqualTo(String value) {
            addCriterion("CC_NAME_KR =", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrNotEqualTo(String value) {
            addCriterion("CC_NAME_KR <>", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrGreaterThan(String value) {
            addCriterion("CC_NAME_KR >", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_KR >=", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrLessThan(String value) {
            addCriterion("CC_NAME_KR <", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_KR <=", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrLike(String value) {
            addCriterion("CC_NAME_KR like", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrNotLike(String value) {
            addCriterion("CC_NAME_KR not like", value, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrIn(List<String> values) {
            addCriterion("CC_NAME_KR in", values, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrNotIn(List<String> values) {
            addCriterion("CC_NAME_KR not in", values, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrBetween(String value1, String value2) {
            addCriterion("CC_NAME_KR between", value1, value2, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameKrNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_KR not between", value1, value2, "ccNameKr");
            return (Criteria) this;
        }

        public Criteria andCcNameUsIsNull() {
            addCriterion("CC_NAME_US is null");
            return (Criteria) this;
        }

        public Criteria andCcNameUsIsNotNull() {
            addCriterion("CC_NAME_US is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameUsEqualTo(String value) {
            addCriterion("CC_NAME_US =", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsNotEqualTo(String value) {
            addCriterion("CC_NAME_US <>", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsGreaterThan(String value) {
            addCriterion("CC_NAME_US >", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_US >=", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsLessThan(String value) {
            addCriterion("CC_NAME_US <", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_US <=", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsLike(String value) {
            addCriterion("CC_NAME_US like", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsNotLike(String value) {
            addCriterion("CC_NAME_US not like", value, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsIn(List<String> values) {
            addCriterion("CC_NAME_US in", values, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsNotIn(List<String> values) {
            addCriterion("CC_NAME_US not in", values, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsBetween(String value1, String value2) {
            addCriterion("CC_NAME_US between", value1, value2, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameUsNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_US not between", value1, value2, "ccNameUs");
            return (Criteria) this;
        }

        public Criteria andCcNameCnIsNull() {
            addCriterion("CC_NAME_CN is null");
            return (Criteria) this;
        }

        public Criteria andCcNameCnIsNotNull() {
            addCriterion("CC_NAME_CN is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameCnEqualTo(String value) {
            addCriterion("CC_NAME_CN =", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnNotEqualTo(String value) {
            addCriterion("CC_NAME_CN <>", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnGreaterThan(String value) {
            addCriterion("CC_NAME_CN >", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_CN >=", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnLessThan(String value) {
            addCriterion("CC_NAME_CN <", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_CN <=", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnLike(String value) {
            addCriterion("CC_NAME_CN like", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnNotLike(String value) {
            addCriterion("CC_NAME_CN not like", value, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnIn(List<String> values) {
            addCriterion("CC_NAME_CN in", values, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnNotIn(List<String> values) {
            addCriterion("CC_NAME_CN not in", values, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnBetween(String value1, String value2) {
            addCriterion("CC_NAME_CN between", value1, value2, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameCnNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_CN not between", value1, value2, "ccNameCn");
            return (Criteria) this;
        }

        public Criteria andCcNameJpIsNull() {
            addCriterion("CC_NAME_JP is null");
            return (Criteria) this;
        }

        public Criteria andCcNameJpIsNotNull() {
            addCriterion("CC_NAME_JP is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameJpEqualTo(String value) {
            addCriterion("CC_NAME_JP =", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpNotEqualTo(String value) {
            addCriterion("CC_NAME_JP <>", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpGreaterThan(String value) {
            addCriterion("CC_NAME_JP >", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_JP >=", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpLessThan(String value) {
            addCriterion("CC_NAME_JP <", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_JP <=", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpLike(String value) {
            addCriterion("CC_NAME_JP like", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpNotLike(String value) {
            addCriterion("CC_NAME_JP not like", value, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpIn(List<String> values) {
            addCriterion("CC_NAME_JP in", values, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpNotIn(List<String> values) {
            addCriterion("CC_NAME_JP not in", values, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpBetween(String value1, String value2) {
            addCriterion("CC_NAME_JP between", value1, value2, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameJpNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_JP not between", value1, value2, "ccNameJp");
            return (Criteria) this;
        }

        public Criteria andCcNameIdIsNull() {
            addCriterion("CC_NAME_ID is null");
            return (Criteria) this;
        }

        public Criteria andCcNameIdIsNotNull() {
            addCriterion("CC_NAME_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameIdEqualTo(String value) {
            addCriterion("CC_NAME_ID =", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdNotEqualTo(String value) {
            addCriterion("CC_NAME_ID <>", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdGreaterThan(String value) {
            addCriterion("CC_NAME_ID >", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_ID >=", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdLessThan(String value) {
            addCriterion("CC_NAME_ID <", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_ID <=", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdLike(String value) {
            addCriterion("CC_NAME_ID like", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdNotLike(String value) {
            addCriterion("CC_NAME_ID not like", value, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdIn(List<String> values) {
            addCriterion("CC_NAME_ID in", values, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdNotIn(List<String> values) {
            addCriterion("CC_NAME_ID not in", values, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdBetween(String value1, String value2) {
            addCriterion("CC_NAME_ID between", value1, value2, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameIdNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_ID not between", value1, value2, "ccNameId");
            return (Criteria) this;
        }

        public Criteria andCcNameFrIsNull() {
            addCriterion("CC_NAME_FR is null");
            return (Criteria) this;
        }

        public Criteria andCcNameFrIsNotNull() {
            addCriterion("CC_NAME_FR is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameFrEqualTo(String value) {
            addCriterion("CC_NAME_FR =", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrNotEqualTo(String value) {
            addCriterion("CC_NAME_FR <>", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrGreaterThan(String value) {
            addCriterion("CC_NAME_FR >", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_FR >=", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrLessThan(String value) {
            addCriterion("CC_NAME_FR <", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_FR <=", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrLike(String value) {
            addCriterion("CC_NAME_FR like", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrNotLike(String value) {
            addCriterion("CC_NAME_FR not like", value, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrIn(List<String> values) {
            addCriterion("CC_NAME_FR in", values, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrNotIn(List<String> values) {
            addCriterion("CC_NAME_FR not in", values, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrBetween(String value1, String value2) {
            addCriterion("CC_NAME_FR between", value1, value2, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameFrNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_FR not between", value1, value2, "ccNameFr");
            return (Criteria) this;
        }

        public Criteria andCcNameEsIsNull() {
            addCriterion("CC_NAME_ES is null");
            return (Criteria) this;
        }

        public Criteria andCcNameEsIsNotNull() {
            addCriterion("CC_NAME_ES is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameEsEqualTo(String value) {
            addCriterion("CC_NAME_ES =", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsNotEqualTo(String value) {
            addCriterion("CC_NAME_ES <>", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsGreaterThan(String value) {
            addCriterion("CC_NAME_ES >", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_ES >=", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsLessThan(String value) {
            addCriterion("CC_NAME_ES <", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_ES <=", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsLike(String value) {
            addCriterion("CC_NAME_ES like", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsNotLike(String value) {
            addCriterion("CC_NAME_ES not like", value, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsIn(List<String> values) {
            addCriterion("CC_NAME_ES in", values, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsNotIn(List<String> values) {
            addCriterion("CC_NAME_ES not in", values, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsBetween(String value1, String value2) {
            addCriterion("CC_NAME_ES between", value1, value2, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameEsNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_ES not between", value1, value2, "ccNameEs");
            return (Criteria) this;
        }

        public Criteria andCcNameRuIsNull() {
            addCriterion("CC_NAME_RU is null");
            return (Criteria) this;
        }

        public Criteria andCcNameRuIsNotNull() {
            addCriterion("CC_NAME_RU is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameRuEqualTo(String value) {
            addCriterion("CC_NAME_RU =", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuNotEqualTo(String value) {
            addCriterion("CC_NAME_RU <>", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuGreaterThan(String value) {
            addCriterion("CC_NAME_RU >", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_RU >=", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuLessThan(String value) {
            addCriterion("CC_NAME_RU <", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_RU <=", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuLike(String value) {
            addCriterion("CC_NAME_RU like", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuNotLike(String value) {
            addCriterion("CC_NAME_RU not like", value, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuIn(List<String> values) {
            addCriterion("CC_NAME_RU in", values, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuNotIn(List<String> values) {
            addCriterion("CC_NAME_RU not in", values, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuBetween(String value1, String value2) {
            addCriterion("CC_NAME_RU between", value1, value2, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameRuNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_RU not between", value1, value2, "ccNameRu");
            return (Criteria) this;
        }

        public Criteria andCcNameDeIsNull() {
            addCriterion("CC_NAME_DE is null");
            return (Criteria) this;
        }

        public Criteria andCcNameDeIsNotNull() {
            addCriterion("CC_NAME_DE is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameDeEqualTo(String value) {
            addCriterion("CC_NAME_DE =", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeNotEqualTo(String value) {
            addCriterion("CC_NAME_DE <>", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeGreaterThan(String value) {
            addCriterion("CC_NAME_DE >", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_DE >=", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeLessThan(String value) {
            addCriterion("CC_NAME_DE <", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_DE <=", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeLike(String value) {
            addCriterion("CC_NAME_DE like", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeNotLike(String value) {
            addCriterion("CC_NAME_DE not like", value, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeIn(List<String> values) {
            addCriterion("CC_NAME_DE in", values, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeNotIn(List<String> values) {
            addCriterion("CC_NAME_DE not in", values, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeBetween(String value1, String value2) {
            addCriterion("CC_NAME_DE between", value1, value2, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameDeNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_DE not between", value1, value2, "ccNameDe");
            return (Criteria) this;
        }

        public Criteria andCcNameAuIsNull() {
            addCriterion("CC_NAME_AU is null");
            return (Criteria) this;
        }

        public Criteria andCcNameAuIsNotNull() {
            addCriterion("CC_NAME_AU is not null");
            return (Criteria) this;
        }

        public Criteria andCcNameAuEqualTo(String value) {
            addCriterion("CC_NAME_AU =", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuNotEqualTo(String value) {
            addCriterion("CC_NAME_AU <>", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuGreaterThan(String value) {
            addCriterion("CC_NAME_AU >", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuGreaterThanOrEqualTo(String value) {
            addCriterion("CC_NAME_AU >=", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuLessThan(String value) {
            addCriterion("CC_NAME_AU <", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuLessThanOrEqualTo(String value) {
            addCriterion("CC_NAME_AU <=", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuLike(String value) {
            addCriterion("CC_NAME_AU like", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuNotLike(String value) {
            addCriterion("CC_NAME_AU not like", value, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuIn(List<String> values) {
            addCriterion("CC_NAME_AU in", values, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuNotIn(List<String> values) {
            addCriterion("CC_NAME_AU not in", values, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuBetween(String value1, String value2) {
            addCriterion("CC_NAME_AU between", value1, value2, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcNameAuNotBetween(String value1, String value2) {
            addCriterion("CC_NAME_AU not between", value1, value2, "ccNameAu");
            return (Criteria) this;
        }

        public Criteria andCcSortIsNull() {
            addCriterion("CC_SORT is null");
            return (Criteria) this;
        }

        public Criteria andCcSortIsNotNull() {
            addCriterion("CC_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andCcSortEqualTo(Integer value) {
            addCriterion("CC_SORT =", value, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortNotEqualTo(Integer value) {
            addCriterion("CC_SORT <>", value, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortGreaterThan(Integer value) {
            addCriterion("CC_SORT >", value, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("CC_SORT >=", value, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortLessThan(Integer value) {
            addCriterion("CC_SORT <", value, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortLessThanOrEqualTo(Integer value) {
            addCriterion("CC_SORT <=", value, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortIn(List<Integer> values) {
            addCriterion("CC_SORT in", values, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortNotIn(List<Integer> values) {
            addCriterion("CC_SORT not in", values, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortBetween(Integer value1, Integer value2) {
            addCriterion("CC_SORT between", value1, value2, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcSortNotBetween(Integer value1, Integer value2) {
            addCriterion("CC_SORT not between", value1, value2, "ccSort");
            return (Criteria) this;
        }

        public Criteria andCcUseIsNull() {
            addCriterion("CC_USE is null");
            return (Criteria) this;
        }

        public Criteria andCcUseIsNotNull() {
            addCriterion("CC_USE is not null");
            return (Criteria) this;
        }

        public Criteria andCcUseEqualTo(String value) {
            addCriterion("CC_USE =", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseNotEqualTo(String value) {
            addCriterion("CC_USE <>", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseGreaterThan(String value) {
            addCriterion("CC_USE >", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseGreaterThanOrEqualTo(String value) {
            addCriterion("CC_USE >=", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseLessThan(String value) {
            addCriterion("CC_USE <", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseLessThanOrEqualTo(String value) {
            addCriterion("CC_USE <=", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseLike(String value) {
            addCriterion("CC_USE like", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseNotLike(String value) {
            addCriterion("CC_USE not like", value, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseIn(List<String> values) {
            addCriterion("CC_USE in", values, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseNotIn(List<String> values) {
            addCriterion("CC_USE not in", values, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseBetween(String value1, String value2) {
            addCriterion("CC_USE between", value1, value2, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcUseNotBetween(String value1, String value2) {
            addCriterion("CC_USE not between", value1, value2, "ccUse");
            return (Criteria) this;
        }

        public Criteria andCcEtcIsNull() {
            addCriterion("CC_ETC is null");
            return (Criteria) this;
        }

        public Criteria andCcEtcIsNotNull() {
            addCriterion("CC_ETC is not null");
            return (Criteria) this;
        }

        public Criteria andCcEtcEqualTo(String value) {
            addCriterion("CC_ETC =", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcNotEqualTo(String value) {
            addCriterion("CC_ETC <>", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcGreaterThan(String value) {
            addCriterion("CC_ETC >", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcGreaterThanOrEqualTo(String value) {
            addCriterion("CC_ETC >=", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcLessThan(String value) {
            addCriterion("CC_ETC <", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcLessThanOrEqualTo(String value) {
            addCriterion("CC_ETC <=", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcLike(String value) {
            addCriterion("CC_ETC like", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcNotLike(String value) {
            addCriterion("CC_ETC not like", value, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcIn(List<String> values) {
            addCriterion("CC_ETC in", values, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcNotIn(List<String> values) {
            addCriterion("CC_ETC not in", values, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcBetween(String value1, String value2) {
            addCriterion("CC_ETC between", value1, value2, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcEtcNotBetween(String value1, String value2) {
            addCriterion("CC_ETC not between", value1, value2, "ccEtc");
            return (Criteria) this;
        }

        public Criteria andCcImg1IsNull() {
            addCriterion("CC_IMG1 is null");
            return (Criteria) this;
        }

        public Criteria andCcImg1IsNotNull() {
            addCriterion("CC_IMG1 is not null");
            return (Criteria) this;
        }

        public Criteria andCcImg1EqualTo(String value) {
            addCriterion("CC_IMG1 =", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1NotEqualTo(String value) {
            addCriterion("CC_IMG1 <>", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1GreaterThan(String value) {
            addCriterion("CC_IMG1 >", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1GreaterThanOrEqualTo(String value) {
            addCriterion("CC_IMG1 >=", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1LessThan(String value) {
            addCriterion("CC_IMG1 <", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1LessThanOrEqualTo(String value) {
            addCriterion("CC_IMG1 <=", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1Like(String value) {
            addCriterion("CC_IMG1 like", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1NotLike(String value) {
            addCriterion("CC_IMG1 not like", value, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1In(List<String> values) {
            addCriterion("CC_IMG1 in", values, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1NotIn(List<String> values) {
            addCriterion("CC_IMG1 not in", values, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1Between(String value1, String value2) {
            addCriterion("CC_IMG1 between", value1, value2, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg1NotBetween(String value1, String value2) {
            addCriterion("CC_IMG1 not between", value1, value2, "ccImg1");
            return (Criteria) this;
        }

        public Criteria andCcImg2IsNull() {
            addCriterion("CC_IMG2 is null");
            return (Criteria) this;
        }

        public Criteria andCcImg2IsNotNull() {
            addCriterion("CC_IMG2 is not null");
            return (Criteria) this;
        }

        public Criteria andCcImg2EqualTo(String value) {
            addCriterion("CC_IMG2 =", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2NotEqualTo(String value) {
            addCriterion("CC_IMG2 <>", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2GreaterThan(String value) {
            addCriterion("CC_IMG2 >", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2GreaterThanOrEqualTo(String value) {
            addCriterion("CC_IMG2 >=", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2LessThan(String value) {
            addCriterion("CC_IMG2 <", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2LessThanOrEqualTo(String value) {
            addCriterion("CC_IMG2 <=", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2Like(String value) {
            addCriterion("CC_IMG2 like", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2NotLike(String value) {
            addCriterion("CC_IMG2 not like", value, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2In(List<String> values) {
            addCriterion("CC_IMG2 in", values, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2NotIn(List<String> values) {
            addCriterion("CC_IMG2 not in", values, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2Between(String value1, String value2) {
            addCriterion("CC_IMG2 between", value1, value2, "ccImg2");
            return (Criteria) this;
        }

        public Criteria andCcImg2NotBetween(String value1, String value2) {
            addCriterion("CC_IMG2 not between", value1, value2, "ccImg2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMM_CODE
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}