package com.atlsmall.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderCart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_NO
     *
     * @mbggenerated
     */
    private Long ocNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.O_NO
     *
     * @mbggenerated
     */
    private Long oNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.P_CODE
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NO
     *
     * @mbggenerated
     */
    private Long ocOptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_P_NAME
     *
     * @mbggenerated
     */
    private String ocPName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM1
     *
     * @mbggenerated
     */
    private String ocOptNm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM2
     *
     * @mbggenerated
     */
    private String ocOptNm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM3
     *
     * @mbggenerated
     */
    private String ocOptNm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM4
     *
     * @mbggenerated
     */
    private String ocOptNm4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM5
     *
     * @mbggenerated
     */
    private String ocOptNm5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM6
     *
     * @mbggenerated
     */
    private String ocOptNm6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM7
     *
     * @mbggenerated
     */
    private String ocOptNm7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM8
     *
     * @mbggenerated
     */
    private String ocOptNm8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM9
     *
     * @mbggenerated
     */
    private String ocOptNm9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_NM10
     *
     * @mbggenerated
     */
    private String ocOptNm10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR1
     *
     * @mbggenerated
     */
    private String ocOptAttr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR2
     *
     * @mbggenerated
     */
    private String ocOptAttr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR3
     *
     * @mbggenerated
     */
    private String ocOptAttr3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR4
     *
     * @mbggenerated
     */
    private String ocOptAttr4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR5
     *
     * @mbggenerated
     */
    private String ocOptAttr5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR6
     *
     * @mbggenerated
     */
    private String ocOptAttr6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR7
     *
     * @mbggenerated
     */
    private String ocOptAttr7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR8
     *
     * @mbggenerated
     */
    private String ocOptAttr8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR9
     *
     * @mbggenerated
     */
    private String ocOptAttr9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ATTR10
     *
     * @mbggenerated
     */
    private String ocOptAttr10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_QTY
     *
     * @mbggenerated
     */
    private Long ocQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_STOCK_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocStockPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_STOCK_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocStockCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_POINT
     *
     * @mbggenerated
     */
    private BigDecimal ocPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_CUR_POINT
     *
     * @mbggenerated
     */
    private BigDecimal ocCurPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_TYPE
     *
     * @mbggenerated
     */
    private String ocDeliveryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocDeliveryPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocDeliveryCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_EXP
     *
     * @mbggenerated
     */
    private String ocDeliveryExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ADD_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocOptAddPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_OPT_ADD_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal ocOptAddCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_STATUS
     *
     * @mbggenerated
     */
    private String ocDeliveryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_ORDER_STATUS
     *
     * @mbggenerated
     */
    private String ocOrderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_COM
     *
     * @mbggenerated
     */
    private String ocDeliveryCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_NUM
     *
     * @mbggenerated
     */
    private String ocDeliveryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_ST_DT
     *
     * @mbggenerated
     */
    private Date ocDeliveryStDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_DELIVERY_END_DT
     *
     * @mbggenerated
     */
    private Date ocDeliveryEndDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_C_REQ_DT
     *
     * @mbggenerated
     */
    private Date ocCReqDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_C_REG_DT
     *
     * @mbggenerated
     */
    private Date ocCRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_S_REQ_DT
     *
     * @mbggenerated
     */
    private Date ocSReqDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_S_REG_DT
     *
     * @mbggenerated
     */
    private Date ocSRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_R_REQ_DT
     *
     * @mbggenerated
     */
    private Date ocRReqDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_R_REG_DT
     *
     * @mbggenerated
     */
    private Date ocRRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_T_REQ_DT
     *
     * @mbggenerated
     */
    private Date ocTReqDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_T_REG_DT
     *
     * @mbggenerated
     */
    private Date ocTRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_P_BAESONG_TYPE
     *
     * @mbggenerated
     */
    private String ocPBaesongType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_E_REG_DT
     *
     * @mbggenerated
     */
    private Date ocERegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_REG_DT
     *
     * @mbggenerated
     */
    private Date ocRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_MOD_NO
     *
     * @mbggenerated
     */
    private Long ocModNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CART.OC_MOD_DT
     *
     * @mbggenerated
     */
    private Date ocModDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_NO
     *
     * @return the value of ORDER_CART.OC_NO
     *
     * @mbggenerated
     */
    public Long getOcNo() {
        return ocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_NO
     *
     * @param ocNo the value for ORDER_CART.OC_NO
     *
     * @mbggenerated
     */
    public void setOcNo(Long ocNo) {
        this.ocNo = ocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.O_NO
     *
     * @return the value of ORDER_CART.O_NO
     *
     * @mbggenerated
     */
    public Long getoNo() {
        return oNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.O_NO
     *
     * @param oNo the value for ORDER_CART.O_NO
     *
     * @mbggenerated
     */
    public void setoNo(Long oNo) {
        this.oNo = oNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.P_CODE
     *
     * @return the value of ORDER_CART.P_CODE
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.P_CODE
     *
     * @param pCode the value for ORDER_CART.P_CODE
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NO
     *
     * @return the value of ORDER_CART.OC_OPT_NO
     *
     * @mbggenerated
     */
    public Long getOcOptNo() {
        return ocOptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NO
     *
     * @param ocOptNo the value for ORDER_CART.OC_OPT_NO
     *
     * @mbggenerated
     */
    public void setOcOptNo(Long ocOptNo) {
        this.ocOptNo = ocOptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_P_NAME
     *
     * @return the value of ORDER_CART.OC_P_NAME
     *
     * @mbggenerated
     */
    public String getOcPName() {
        return ocPName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_P_NAME
     *
     * @param ocPName the value for ORDER_CART.OC_P_NAME
     *
     * @mbggenerated
     */
    public void setOcPName(String ocPName) {
        this.ocPName = ocPName == null ? null : ocPName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM1
     *
     * @return the value of ORDER_CART.OC_OPT_NM1
     *
     * @mbggenerated
     */
    public String getOcOptNm1() {
        return ocOptNm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM1
     *
     * @param ocOptNm1 the value for ORDER_CART.OC_OPT_NM1
     *
     * @mbggenerated
     */
    public void setOcOptNm1(String ocOptNm1) {
        this.ocOptNm1 = ocOptNm1 == null ? null : ocOptNm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM2
     *
     * @return the value of ORDER_CART.OC_OPT_NM2
     *
     * @mbggenerated
     */
    public String getOcOptNm2() {
        return ocOptNm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM2
     *
     * @param ocOptNm2 the value for ORDER_CART.OC_OPT_NM2
     *
     * @mbggenerated
     */
    public void setOcOptNm2(String ocOptNm2) {
        this.ocOptNm2 = ocOptNm2 == null ? null : ocOptNm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM3
     *
     * @return the value of ORDER_CART.OC_OPT_NM3
     *
     * @mbggenerated
     */
    public String getOcOptNm3() {
        return ocOptNm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM3
     *
     * @param ocOptNm3 the value for ORDER_CART.OC_OPT_NM3
     *
     * @mbggenerated
     */
    public void setOcOptNm3(String ocOptNm3) {
        this.ocOptNm3 = ocOptNm3 == null ? null : ocOptNm3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM4
     *
     * @return the value of ORDER_CART.OC_OPT_NM4
     *
     * @mbggenerated
     */
    public String getOcOptNm4() {
        return ocOptNm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM4
     *
     * @param ocOptNm4 the value for ORDER_CART.OC_OPT_NM4
     *
     * @mbggenerated
     */
    public void setOcOptNm4(String ocOptNm4) {
        this.ocOptNm4 = ocOptNm4 == null ? null : ocOptNm4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM5
     *
     * @return the value of ORDER_CART.OC_OPT_NM5
     *
     * @mbggenerated
     */
    public String getOcOptNm5() {
        return ocOptNm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM5
     *
     * @param ocOptNm5 the value for ORDER_CART.OC_OPT_NM5
     *
     * @mbggenerated
     */
    public void setOcOptNm5(String ocOptNm5) {
        this.ocOptNm5 = ocOptNm5 == null ? null : ocOptNm5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM6
     *
     * @return the value of ORDER_CART.OC_OPT_NM6
     *
     * @mbggenerated
     */
    public String getOcOptNm6() {
        return ocOptNm6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM6
     *
     * @param ocOptNm6 the value for ORDER_CART.OC_OPT_NM6
     *
     * @mbggenerated
     */
    public void setOcOptNm6(String ocOptNm6) {
        this.ocOptNm6 = ocOptNm6 == null ? null : ocOptNm6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM7
     *
     * @return the value of ORDER_CART.OC_OPT_NM7
     *
     * @mbggenerated
     */
    public String getOcOptNm7() {
        return ocOptNm7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM7
     *
     * @param ocOptNm7 the value for ORDER_CART.OC_OPT_NM7
     *
     * @mbggenerated
     */
    public void setOcOptNm7(String ocOptNm7) {
        this.ocOptNm7 = ocOptNm7 == null ? null : ocOptNm7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM8
     *
     * @return the value of ORDER_CART.OC_OPT_NM8
     *
     * @mbggenerated
     */
    public String getOcOptNm8() {
        return ocOptNm8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM8
     *
     * @param ocOptNm8 the value for ORDER_CART.OC_OPT_NM8
     *
     * @mbggenerated
     */
    public void setOcOptNm8(String ocOptNm8) {
        this.ocOptNm8 = ocOptNm8 == null ? null : ocOptNm8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM9
     *
     * @return the value of ORDER_CART.OC_OPT_NM9
     *
     * @mbggenerated
     */
    public String getOcOptNm9() {
        return ocOptNm9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM9
     *
     * @param ocOptNm9 the value for ORDER_CART.OC_OPT_NM9
     *
     * @mbggenerated
     */
    public void setOcOptNm9(String ocOptNm9) {
        this.ocOptNm9 = ocOptNm9 == null ? null : ocOptNm9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_NM10
     *
     * @return the value of ORDER_CART.OC_OPT_NM10
     *
     * @mbggenerated
     */
    public String getOcOptNm10() {
        return ocOptNm10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_NM10
     *
     * @param ocOptNm10 the value for ORDER_CART.OC_OPT_NM10
     *
     * @mbggenerated
     */
    public void setOcOptNm10(String ocOptNm10) {
        this.ocOptNm10 = ocOptNm10 == null ? null : ocOptNm10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR1
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR1
     *
     * @mbggenerated
     */
    public String getOcOptAttr1() {
        return ocOptAttr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR1
     *
     * @param ocOptAttr1 the value for ORDER_CART.OC_OPT_ATTR1
     *
     * @mbggenerated
     */
    public void setOcOptAttr1(String ocOptAttr1) {
        this.ocOptAttr1 = ocOptAttr1 == null ? null : ocOptAttr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR2
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR2
     *
     * @mbggenerated
     */
    public String getOcOptAttr2() {
        return ocOptAttr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR2
     *
     * @param ocOptAttr2 the value for ORDER_CART.OC_OPT_ATTR2
     *
     * @mbggenerated
     */
    public void setOcOptAttr2(String ocOptAttr2) {
        this.ocOptAttr2 = ocOptAttr2 == null ? null : ocOptAttr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR3
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR3
     *
     * @mbggenerated
     */
    public String getOcOptAttr3() {
        return ocOptAttr3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR3
     *
     * @param ocOptAttr3 the value for ORDER_CART.OC_OPT_ATTR3
     *
     * @mbggenerated
     */
    public void setOcOptAttr3(String ocOptAttr3) {
        this.ocOptAttr3 = ocOptAttr3 == null ? null : ocOptAttr3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR4
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR4
     *
     * @mbggenerated
     */
    public String getOcOptAttr4() {
        return ocOptAttr4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR4
     *
     * @param ocOptAttr4 the value for ORDER_CART.OC_OPT_ATTR4
     *
     * @mbggenerated
     */
    public void setOcOptAttr4(String ocOptAttr4) {
        this.ocOptAttr4 = ocOptAttr4 == null ? null : ocOptAttr4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR5
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR5
     *
     * @mbggenerated
     */
    public String getOcOptAttr5() {
        return ocOptAttr5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR5
     *
     * @param ocOptAttr5 the value for ORDER_CART.OC_OPT_ATTR5
     *
     * @mbggenerated
     */
    public void setOcOptAttr5(String ocOptAttr5) {
        this.ocOptAttr5 = ocOptAttr5 == null ? null : ocOptAttr5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR6
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR6
     *
     * @mbggenerated
     */
    public String getOcOptAttr6() {
        return ocOptAttr6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR6
     *
     * @param ocOptAttr6 the value for ORDER_CART.OC_OPT_ATTR6
     *
     * @mbggenerated
     */
    public void setOcOptAttr6(String ocOptAttr6) {
        this.ocOptAttr6 = ocOptAttr6 == null ? null : ocOptAttr6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR7
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR7
     *
     * @mbggenerated
     */
    public String getOcOptAttr7() {
        return ocOptAttr7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR7
     *
     * @param ocOptAttr7 the value for ORDER_CART.OC_OPT_ATTR7
     *
     * @mbggenerated
     */
    public void setOcOptAttr7(String ocOptAttr7) {
        this.ocOptAttr7 = ocOptAttr7 == null ? null : ocOptAttr7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR8
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR8
     *
     * @mbggenerated
     */
    public String getOcOptAttr8() {
        return ocOptAttr8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR8
     *
     * @param ocOptAttr8 the value for ORDER_CART.OC_OPT_ATTR8
     *
     * @mbggenerated
     */
    public void setOcOptAttr8(String ocOptAttr8) {
        this.ocOptAttr8 = ocOptAttr8 == null ? null : ocOptAttr8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR9
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR9
     *
     * @mbggenerated
     */
    public String getOcOptAttr9() {
        return ocOptAttr9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR9
     *
     * @param ocOptAttr9 the value for ORDER_CART.OC_OPT_ATTR9
     *
     * @mbggenerated
     */
    public void setOcOptAttr9(String ocOptAttr9) {
        this.ocOptAttr9 = ocOptAttr9 == null ? null : ocOptAttr9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ATTR10
     *
     * @return the value of ORDER_CART.OC_OPT_ATTR10
     *
     * @mbggenerated
     */
    public String getOcOptAttr10() {
        return ocOptAttr10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ATTR10
     *
     * @param ocOptAttr10 the value for ORDER_CART.OC_OPT_ATTR10
     *
     * @mbggenerated
     */
    public void setOcOptAttr10(String ocOptAttr10) {
        this.ocOptAttr10 = ocOptAttr10 == null ? null : ocOptAttr10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_QTY
     *
     * @return the value of ORDER_CART.OC_QTY
     *
     * @mbggenerated
     */
    public Long getOcQty() {
        return ocQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_QTY
     *
     * @param ocQty the value for ORDER_CART.OC_QTY
     *
     * @mbggenerated
     */
    public void setOcQty(Long ocQty) {
        this.ocQty = ocQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_STOCK_PRICE
     *
     * @return the value of ORDER_CART.OC_STOCK_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcStockPrice() {
        return ocStockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_STOCK_PRICE
     *
     * @param ocStockPrice the value for ORDER_CART.OC_STOCK_PRICE
     *
     * @mbggenerated
     */
    public void setOcStockPrice(BigDecimal ocStockPrice) {
        this.ocStockPrice = ocStockPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_STOCK_CUR_PRICE
     *
     * @return the value of ORDER_CART.OC_STOCK_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcStockCurPrice() {
        return ocStockCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_STOCK_CUR_PRICE
     *
     * @param ocStockCurPrice the value for ORDER_CART.OC_STOCK_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setOcStockCurPrice(BigDecimal ocStockCurPrice) {
        this.ocStockCurPrice = ocStockCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_PRICE
     *
     * @return the value of ORDER_CART.OC_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcPrice() {
        return ocPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_PRICE
     *
     * @param ocPrice the value for ORDER_CART.OC_PRICE
     *
     * @mbggenerated
     */
    public void setOcPrice(BigDecimal ocPrice) {
        this.ocPrice = ocPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_CUR_PRICE
     *
     * @return the value of ORDER_CART.OC_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcCurPrice() {
        return ocCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_CUR_PRICE
     *
     * @param ocCurPrice the value for ORDER_CART.OC_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setOcCurPrice(BigDecimal ocCurPrice) {
        this.ocCurPrice = ocCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_POINT
     *
     * @return the value of ORDER_CART.OC_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getOcPoint() {
        return ocPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_POINT
     *
     * @param ocPoint the value for ORDER_CART.OC_POINT
     *
     * @mbggenerated
     */
    public void setOcPoint(BigDecimal ocPoint) {
        this.ocPoint = ocPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_CUR_POINT
     *
     * @return the value of ORDER_CART.OC_CUR_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getOcCurPoint() {
        return ocCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_CUR_POINT
     *
     * @param ocCurPoint the value for ORDER_CART.OC_CUR_POINT
     *
     * @mbggenerated
     */
    public void setOcCurPoint(BigDecimal ocCurPoint) {
        this.ocCurPoint = ocCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_TYPE
     *
     * @return the value of ORDER_CART.OC_DELIVERY_TYPE
     *
     * @mbggenerated
     */
    public String getOcDeliveryType() {
        return ocDeliveryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_TYPE
     *
     * @param ocDeliveryType the value for ORDER_CART.OC_DELIVERY_TYPE
     *
     * @mbggenerated
     */
    public void setOcDeliveryType(String ocDeliveryType) {
        this.ocDeliveryType = ocDeliveryType == null ? null : ocDeliveryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_PRICE
     *
     * @return the value of ORDER_CART.OC_DELIVERY_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcDeliveryPrice() {
        return ocDeliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_PRICE
     *
     * @param ocDeliveryPrice the value for ORDER_CART.OC_DELIVERY_PRICE
     *
     * @mbggenerated
     */
    public void setOcDeliveryPrice(BigDecimal ocDeliveryPrice) {
        this.ocDeliveryPrice = ocDeliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_CUR_PRICE
     *
     * @return the value of ORDER_CART.OC_DELIVERY_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcDeliveryCurPrice() {
        return ocDeliveryCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_CUR_PRICE
     *
     * @param ocDeliveryCurPrice the value for ORDER_CART.OC_DELIVERY_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setOcDeliveryCurPrice(BigDecimal ocDeliveryCurPrice) {
        this.ocDeliveryCurPrice = ocDeliveryCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_EXP
     *
     * @return the value of ORDER_CART.OC_DELIVERY_EXP
     *
     * @mbggenerated
     */
    public String getOcDeliveryExp() {
        return ocDeliveryExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_EXP
     *
     * @param ocDeliveryExp the value for ORDER_CART.OC_DELIVERY_EXP
     *
     * @mbggenerated
     */
    public void setOcDeliveryExp(String ocDeliveryExp) {
        this.ocDeliveryExp = ocDeliveryExp == null ? null : ocDeliveryExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ADD_PRICE
     *
     * @return the value of ORDER_CART.OC_OPT_ADD_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcOptAddPrice() {
        return ocOptAddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ADD_PRICE
     *
     * @param ocOptAddPrice the value for ORDER_CART.OC_OPT_ADD_PRICE
     *
     * @mbggenerated
     */
    public void setOcOptAddPrice(BigDecimal ocOptAddPrice) {
        this.ocOptAddPrice = ocOptAddPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_OPT_ADD_CUR_PRICE
     *
     * @return the value of ORDER_CART.OC_OPT_ADD_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getOcOptAddCurPrice() {
        return ocOptAddCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_OPT_ADD_CUR_PRICE
     *
     * @param ocOptAddCurPrice the value for ORDER_CART.OC_OPT_ADD_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setOcOptAddCurPrice(BigDecimal ocOptAddCurPrice) {
        this.ocOptAddCurPrice = ocOptAddCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_STATUS
     *
     * @return the value of ORDER_CART.OC_DELIVERY_STATUS
     *
     * @mbggenerated
     */
    public String getOcDeliveryStatus() {
        return ocDeliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_STATUS
     *
     * @param ocDeliveryStatus the value for ORDER_CART.OC_DELIVERY_STATUS
     *
     * @mbggenerated
     */
    public void setOcDeliveryStatus(String ocDeliveryStatus) {
        this.ocDeliveryStatus = ocDeliveryStatus == null ? null : ocDeliveryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_ORDER_STATUS
     *
     * @return the value of ORDER_CART.OC_ORDER_STATUS
     *
     * @mbggenerated
     */
    public String getOcOrderStatus() {
        return ocOrderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_ORDER_STATUS
     *
     * @param ocOrderStatus the value for ORDER_CART.OC_ORDER_STATUS
     *
     * @mbggenerated
     */
    public void setOcOrderStatus(String ocOrderStatus) {
        this.ocOrderStatus = ocOrderStatus == null ? null : ocOrderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_COM
     *
     * @return the value of ORDER_CART.OC_DELIVERY_COM
     *
     * @mbggenerated
     */
    public String getOcDeliveryCom() {
        return ocDeliveryCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_COM
     *
     * @param ocDeliveryCom the value for ORDER_CART.OC_DELIVERY_COM
     *
     * @mbggenerated
     */
    public void setOcDeliveryCom(String ocDeliveryCom) {
        this.ocDeliveryCom = ocDeliveryCom == null ? null : ocDeliveryCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_NUM
     *
     * @return the value of ORDER_CART.OC_DELIVERY_NUM
     *
     * @mbggenerated
     */
    public String getOcDeliveryNum() {
        return ocDeliveryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_NUM
     *
     * @param ocDeliveryNum the value for ORDER_CART.OC_DELIVERY_NUM
     *
     * @mbggenerated
     */
    public void setOcDeliveryNum(String ocDeliveryNum) {
        this.ocDeliveryNum = ocDeliveryNum == null ? null : ocDeliveryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_ST_DT
     *
     * @return the value of ORDER_CART.OC_DELIVERY_ST_DT
     *
     * @mbggenerated
     */
    public Date getOcDeliveryStDt() {
        return ocDeliveryStDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_ST_DT
     *
     * @param ocDeliveryStDt the value for ORDER_CART.OC_DELIVERY_ST_DT
     *
     * @mbggenerated
     */
    public void setOcDeliveryStDt(Date ocDeliveryStDt) {
        this.ocDeliveryStDt = ocDeliveryStDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_DELIVERY_END_DT
     *
     * @return the value of ORDER_CART.OC_DELIVERY_END_DT
     *
     * @mbggenerated
     */
    public Date getOcDeliveryEndDt() {
        return ocDeliveryEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_DELIVERY_END_DT
     *
     * @param ocDeliveryEndDt the value for ORDER_CART.OC_DELIVERY_END_DT
     *
     * @mbggenerated
     */
    public void setOcDeliveryEndDt(Date ocDeliveryEndDt) {
        this.ocDeliveryEndDt = ocDeliveryEndDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_C_REQ_DT
     *
     * @return the value of ORDER_CART.OC_C_REQ_DT
     *
     * @mbggenerated
     */
    public Date getOcCReqDt() {
        return ocCReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_C_REQ_DT
     *
     * @param ocCReqDt the value for ORDER_CART.OC_C_REQ_DT
     *
     * @mbggenerated
     */
    public void setOcCReqDt(Date ocCReqDt) {
        this.ocCReqDt = ocCReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_C_REG_DT
     *
     * @return the value of ORDER_CART.OC_C_REG_DT
     *
     * @mbggenerated
     */
    public Date getOcCRegDt() {
        return ocCRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_C_REG_DT
     *
     * @param ocCRegDt the value for ORDER_CART.OC_C_REG_DT
     *
     * @mbggenerated
     */
    public void setOcCRegDt(Date ocCRegDt) {
        this.ocCRegDt = ocCRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_S_REQ_DT
     *
     * @return the value of ORDER_CART.OC_S_REQ_DT
     *
     * @mbggenerated
     */
    public Date getOcSReqDt() {
        return ocSReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_S_REQ_DT
     *
     * @param ocSReqDt the value for ORDER_CART.OC_S_REQ_DT
     *
     * @mbggenerated
     */
    public void setOcSReqDt(Date ocSReqDt) {
        this.ocSReqDt = ocSReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_S_REG_DT
     *
     * @return the value of ORDER_CART.OC_S_REG_DT
     *
     * @mbggenerated
     */
    public Date getOcSRegDt() {
        return ocSRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_S_REG_DT
     *
     * @param ocSRegDt the value for ORDER_CART.OC_S_REG_DT
     *
     * @mbggenerated
     */
    public void setOcSRegDt(Date ocSRegDt) {
        this.ocSRegDt = ocSRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_R_REQ_DT
     *
     * @return the value of ORDER_CART.OC_R_REQ_DT
     *
     * @mbggenerated
     */
    public Date getOcRReqDt() {
        return ocRReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_R_REQ_DT
     *
     * @param ocRReqDt the value for ORDER_CART.OC_R_REQ_DT
     *
     * @mbggenerated
     */
    public void setOcRReqDt(Date ocRReqDt) {
        this.ocRReqDt = ocRReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_R_REG_DT
     *
     * @return the value of ORDER_CART.OC_R_REG_DT
     *
     * @mbggenerated
     */
    public Date getOcRRegDt() {
        return ocRRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_R_REG_DT
     *
     * @param ocRRegDt the value for ORDER_CART.OC_R_REG_DT
     *
     * @mbggenerated
     */
    public void setOcRRegDt(Date ocRRegDt) {
        this.ocRRegDt = ocRRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_T_REQ_DT
     *
     * @return the value of ORDER_CART.OC_T_REQ_DT
     *
     * @mbggenerated
     */
    public Date getOcTReqDt() {
        return ocTReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_T_REQ_DT
     *
     * @param ocTReqDt the value for ORDER_CART.OC_T_REQ_DT
     *
     * @mbggenerated
     */
    public void setOcTReqDt(Date ocTReqDt) {
        this.ocTReqDt = ocTReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_T_REG_DT
     *
     * @return the value of ORDER_CART.OC_T_REG_DT
     *
     * @mbggenerated
     */
    public Date getOcTRegDt() {
        return ocTRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_T_REG_DT
     *
     * @param ocTRegDt the value for ORDER_CART.OC_T_REG_DT
     *
     * @mbggenerated
     */
    public void setOcTRegDt(Date ocTRegDt) {
        this.ocTRegDt = ocTRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_P_BAESONG_TYPE
     *
     * @return the value of ORDER_CART.OC_P_BAESONG_TYPE
     *
     * @mbggenerated
     */
    public String getOcPBaesongType() {
        return ocPBaesongType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_P_BAESONG_TYPE
     *
     * @param ocPBaesongType the value for ORDER_CART.OC_P_BAESONG_TYPE
     *
     * @mbggenerated
     */
    public void setOcPBaesongType(String ocPBaesongType) {
        this.ocPBaesongType = ocPBaesongType == null ? null : ocPBaesongType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_E_REG_DT
     *
     * @return the value of ORDER_CART.OC_E_REG_DT
     *
     * @mbggenerated
     */
    public Date getOcERegDt() {
        return ocERegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_E_REG_DT
     *
     * @param ocERegDt the value for ORDER_CART.OC_E_REG_DT
     *
     * @mbggenerated
     */
    public void setOcERegDt(Date ocERegDt) {
        this.ocERegDt = ocERegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_REG_DT
     *
     * @return the value of ORDER_CART.OC_REG_DT
     *
     * @mbggenerated
     */
    public Date getOcRegDt() {
        return ocRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_REG_DT
     *
     * @param ocRegDt the value for ORDER_CART.OC_REG_DT
     *
     * @mbggenerated
     */
    public void setOcRegDt(Date ocRegDt) {
        this.ocRegDt = ocRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_MOD_NO
     *
     * @return the value of ORDER_CART.OC_MOD_NO
     *
     * @mbggenerated
     */
    public Long getOcModNo() {
        return ocModNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_MOD_NO
     *
     * @param ocModNo the value for ORDER_CART.OC_MOD_NO
     *
     * @mbggenerated
     */
    public void setOcModNo(Long ocModNo) {
        this.ocModNo = ocModNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CART.OC_MOD_DT
     *
     * @return the value of ORDER_CART.OC_MOD_DT
     *
     * @mbggenerated
     */
    public Date getOcModDt() {
        return ocModDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CART.OC_MOD_DT
     *
     * @param ocModDt the value for ORDER_CART.OC_MOD_DT
     *
     * @mbggenerated
     */
    public void setOcModDt(Date ocModDt) {
        this.ocModDt = ocModDt;
    }
}