package com.atlsmall.entity;

import java.math.BigDecimal;
import java.util.Date;

public class OrderMgr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_NO
     *
     * @mbggenerated
     */
    private Long oNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_KEY
     *
     * @mbggenerated
     */
    private String oKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.M_NO
     *
     * @mbggenerated
     */
    private Long mNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_J_TITLE
     *
     * @mbggenerated
     */
    private String oJTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_J_NAME
     *
     * @mbggenerated
     */
    private String oJName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_J_PHONE
     *
     * @mbggenerated
     */
    private String oJPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_J_HP
     *
     * @mbggenerated
     */
    private String oJHp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_J_MAIL
     *
     * @mbggenerated
     */
    private String oJMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_NAME
     *
     * @mbggenerated
     */
    private String oBName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_PHONE
     *
     * @mbggenerated
     */
    private String oBPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_HP
     *
     * @mbggenerated
     */
    private String oBHp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_MAIL
     *
     * @mbggenerated
     */
    private String oBMail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_ZIP
     *
     * @mbggenerated
     */
    private String oBZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_COUNTRY
     *
     * @mbggenerated
     */
    private String oBCountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_ADDR1
     *
     * @mbggenerated
     */
    private String oBAddr1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_ADDR2
     *
     * @mbggenerated
     */
    private String oBAddr2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_CITY
     *
     * @mbggenerated
     */
    private String oBCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_STATE
     *
     * @mbggenerated
     */
    private String oBState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_PG
     *
     * @mbggenerated
     */
    private String oPg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_SETTLE
     *
     * @mbggenerated
     */
    private String oSettle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_BANK_NAME
     *
     * @mbggenerated
     */
    private String oBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_BANK
     *
     * @mbggenerated
     */
    private String oBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_BANK_ACC
     *
     * @mbggenerated
     */
    private String oBankAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_BANK_VALID_DT
     *
     * @mbggenerated
     */
    private String oBankValidDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DELIVERY_COM
     *
     * @mbggenerated
     */
    private String oDeliveryCom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DELIVERY_NUM
     *
     * @mbggenerated
     */
    private String oDeliveryNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DELIVERY_WEIGHT
     *
     * @mbggenerated
     */
    private String oDeliveryWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DELIVERY_SIZE
     *
     * @mbggenerated
     */
    private String oDeliverySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_POINT
     *
     * @mbggenerated
     */
    private BigDecimal oUsePoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_CUR_POINT
     *
     * @mbggenerated
     */
    private BigDecimal oUseCurPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_COUPON_NUM
     *
     * @mbggenerated
     */
    private String oUseCouponNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_COUPON
     *
     * @mbggenerated
     */
    private BigDecimal oUseCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_CUR_COUPON
     *
     * @mbggenerated
     */
    private BigDecimal oUseCurCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_QTY
     *
     * @mbggenerated
     */
    private Long oTotQty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_DELIVERY_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotDeliveryPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_DELIVERY_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotDeliveryCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TAX_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTaxPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TAX_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTaxCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_MEM_DISCOUNT_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotMemDiscountCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_MEM_DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotMemDiscountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_SPRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotSprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_CUR_SPRICE
     *
     * @mbggenerated
     */
    private BigDecimal oTotCurSprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_MEM_POINT
     *
     * @mbggenerated
     */
    private BigDecimal oTotMemPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_MEM_CUR_POINT
     *
     * @mbggenerated
     */
    private BigDecimal oTotMemCurPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_POINT
     *
     * @mbggenerated
     */
    private BigDecimal oTotPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_TOT_CUR_POINT
     *
     * @mbggenerated
     */
    private BigDecimal oTotCurPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_APPR_NO
     *
     * @mbggenerated
     */
    private String oApprNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_APPR_DT
     *
     * @mbggenerated
     */
    private Date oApprDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_STATUS
     *
     * @mbggenerated
     */
    private String oStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_ADD_POINT
     *
     * @mbggenerated
     */
    private String oAddPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_ESCROW
     *
     * @mbggenerated
     */
    private String oEscrow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_RETURN_BANK
     *
     * @mbggenerated
     */
    private String oReturnBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_RETURN_ACC
     *
     * @mbggenerated
     */
    private String oReturnAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_RETURN_NAME
     *
     * @mbggenerated
     */
    private String oReturnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CEL_NO
     *
     * @mbggenerated
     */
    private String oCelNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CEL_REQ_DT
     *
     * @mbggenerated
     */
    private Date oCelReqDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CEL_REG_DT
     *
     * @mbggenerated
     */
    private Date oCelRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CEL_MEMO
     *
     * @mbggenerated
     */
    private String oCelMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CEL_STATUS
     *
     * @mbggenerated
     */
    private String oCelStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_LNG
     *
     * @mbggenerated
     */
    private String oUseLng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_CUR
     *
     * @mbggenerated
     */
    private String oUseCur;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_CUR_RATE
     *
     * @mbggenerated
     */
    private BigDecimal oUseCurRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_USE_CUR_ORG_RATE
     *
     * @mbggenerated
     */
    private BigDecimal oUseCurOrgRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_FOREIGN_PG_KEY
     *
     * @mbggenerated
     */
    private String oForeignPgKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_FOREIGN_PG_ID
     *
     * @mbggenerated
     */
    private String oForeignPgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_ACC
     *
     * @mbggenerated
     */
    private String oAcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CASH_YN
     *
     * @mbggenerated
     */
    private String oCashYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CASH_AUTH_NO
     *
     * @mbggenerated
     */
    private String oCashAuthNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_CASH_INFO
     *
     * @mbggenerated
     */
    private String oCashInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_SELF_WRITE
     *
     * @mbggenerated
     */
    private String oSelfWrite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_FIRST_YN
     *
     * @mbggenerated
     */
    private String oFirstYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_PATH
     *
     * @mbggenerated
     */
    private String oPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DISCOUNT_RATE
     *
     * @mbggenerated
     */
    private Byte oDiscountRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oDiscountPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_DISCOUNT_CUR_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal oDiscountCurPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_SHIPPING_NO
     *
     * @mbggenerated
     */
    private String oShippingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_WECHAT_TMP
     *
     * @mbggenerated
     */
    private String oWechatTmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_REG_IP
     *
     * @mbggenerated
     */
    private String oRegIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_REG_DT
     *
     * @mbggenerated
     */
    private Date oRegDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_MGR.O_B_MEMO
     *
     * @mbggenerated
     */
    private String oBMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_NO
     *
     * @return the value of ORDER_MGR.O_NO
     *
     * @mbggenerated
     */
    public Long getoNo() {
        return oNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_NO
     *
     * @param oNo the value for ORDER_MGR.O_NO
     *
     * @mbggenerated
     */
    public void setoNo(Long oNo) {
        this.oNo = oNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_KEY
     *
     * @return the value of ORDER_MGR.O_KEY
     *
     * @mbggenerated
     */
    public String getoKey() {
        return oKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_KEY
     *
     * @param oKey the value for ORDER_MGR.O_KEY
     *
     * @mbggenerated
     */
    public void setoKey(String oKey) {
        this.oKey = oKey == null ? null : oKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.M_NO
     *
     * @return the value of ORDER_MGR.M_NO
     *
     * @mbggenerated
     */
    public Long getmNo() {
        return mNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.M_NO
     *
     * @param mNo the value for ORDER_MGR.M_NO
     *
     * @mbggenerated
     */
    public void setmNo(Long mNo) {
        this.mNo = mNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_J_TITLE
     *
     * @return the value of ORDER_MGR.O_J_TITLE
     *
     * @mbggenerated
     */
    public String getoJTitle() {
        return oJTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_J_TITLE
     *
     * @param oJTitle the value for ORDER_MGR.O_J_TITLE
     *
     * @mbggenerated
     */
    public void setoJTitle(String oJTitle) {
        this.oJTitle = oJTitle == null ? null : oJTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_J_NAME
     *
     * @return the value of ORDER_MGR.O_J_NAME
     *
     * @mbggenerated
     */
    public String getoJName() {
        return oJName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_J_NAME
     *
     * @param oJName the value for ORDER_MGR.O_J_NAME
     *
     * @mbggenerated
     */
    public void setoJName(String oJName) {
        this.oJName = oJName == null ? null : oJName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_J_PHONE
     *
     * @return the value of ORDER_MGR.O_J_PHONE
     *
     * @mbggenerated
     */
    public String getoJPhone() {
        return oJPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_J_PHONE
     *
     * @param oJPhone the value for ORDER_MGR.O_J_PHONE
     *
     * @mbggenerated
     */
    public void setoJPhone(String oJPhone) {
        this.oJPhone = oJPhone == null ? null : oJPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_J_HP
     *
     * @return the value of ORDER_MGR.O_J_HP
     *
     * @mbggenerated
     */
    public String getoJHp() {
        return oJHp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_J_HP
     *
     * @param oJHp the value for ORDER_MGR.O_J_HP
     *
     * @mbggenerated
     */
    public void setoJHp(String oJHp) {
        this.oJHp = oJHp == null ? null : oJHp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_J_MAIL
     *
     * @return the value of ORDER_MGR.O_J_MAIL
     *
     * @mbggenerated
     */
    public String getoJMail() {
        return oJMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_J_MAIL
     *
     * @param oJMail the value for ORDER_MGR.O_J_MAIL
     *
     * @mbggenerated
     */
    public void setoJMail(String oJMail) {
        this.oJMail = oJMail == null ? null : oJMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_NAME
     *
     * @return the value of ORDER_MGR.O_B_NAME
     *
     * @mbggenerated
     */
    public String getoBName() {
        return oBName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_NAME
     *
     * @param oBName the value for ORDER_MGR.O_B_NAME
     *
     * @mbggenerated
     */
    public void setoBName(String oBName) {
        this.oBName = oBName == null ? null : oBName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_PHONE
     *
     * @return the value of ORDER_MGR.O_B_PHONE
     *
     * @mbggenerated
     */
    public String getoBPhone() {
        return oBPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_PHONE
     *
     * @param oBPhone the value for ORDER_MGR.O_B_PHONE
     *
     * @mbggenerated
     */
    public void setoBPhone(String oBPhone) {
        this.oBPhone = oBPhone == null ? null : oBPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_HP
     *
     * @return the value of ORDER_MGR.O_B_HP
     *
     * @mbggenerated
     */
    public String getoBHp() {
        return oBHp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_HP
     *
     * @param oBHp the value for ORDER_MGR.O_B_HP
     *
     * @mbggenerated
     */
    public void setoBHp(String oBHp) {
        this.oBHp = oBHp == null ? null : oBHp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_MAIL
     *
     * @return the value of ORDER_MGR.O_B_MAIL
     *
     * @mbggenerated
     */
    public String getoBMail() {
        return oBMail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_MAIL
     *
     * @param oBMail the value for ORDER_MGR.O_B_MAIL
     *
     * @mbggenerated
     */
    public void setoBMail(String oBMail) {
        this.oBMail = oBMail == null ? null : oBMail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_ZIP
     *
     * @return the value of ORDER_MGR.O_B_ZIP
     *
     * @mbggenerated
     */
    public String getoBZip() {
        return oBZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_ZIP
     *
     * @param oBZip the value for ORDER_MGR.O_B_ZIP
     *
     * @mbggenerated
     */
    public void setoBZip(String oBZip) {
        this.oBZip = oBZip == null ? null : oBZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_COUNTRY
     *
     * @return the value of ORDER_MGR.O_B_COUNTRY
     *
     * @mbggenerated
     */
    public String getoBCountry() {
        return oBCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_COUNTRY
     *
     * @param oBCountry the value for ORDER_MGR.O_B_COUNTRY
     *
     * @mbggenerated
     */
    public void setoBCountry(String oBCountry) {
        this.oBCountry = oBCountry == null ? null : oBCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_ADDR1
     *
     * @return the value of ORDER_MGR.O_B_ADDR1
     *
     * @mbggenerated
     */
    public String getoBAddr1() {
        return oBAddr1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_ADDR1
     *
     * @param oBAddr1 the value for ORDER_MGR.O_B_ADDR1
     *
     * @mbggenerated
     */
    public void setoBAddr1(String oBAddr1) {
        this.oBAddr1 = oBAddr1 == null ? null : oBAddr1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_ADDR2
     *
     * @return the value of ORDER_MGR.O_B_ADDR2
     *
     * @mbggenerated
     */
    public String getoBAddr2() {
        return oBAddr2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_ADDR2
     *
     * @param oBAddr2 the value for ORDER_MGR.O_B_ADDR2
     *
     * @mbggenerated
     */
    public void setoBAddr2(String oBAddr2) {
        this.oBAddr2 = oBAddr2 == null ? null : oBAddr2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_CITY
     *
     * @return the value of ORDER_MGR.O_B_CITY
     *
     * @mbggenerated
     */
    public String getoBCity() {
        return oBCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_CITY
     *
     * @param oBCity the value for ORDER_MGR.O_B_CITY
     *
     * @mbggenerated
     */
    public void setoBCity(String oBCity) {
        this.oBCity = oBCity == null ? null : oBCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_STATE
     *
     * @return the value of ORDER_MGR.O_B_STATE
     *
     * @mbggenerated
     */
    public String getoBState() {
        return oBState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_STATE
     *
     * @param oBState the value for ORDER_MGR.O_B_STATE
     *
     * @mbggenerated
     */
    public void setoBState(String oBState) {
        this.oBState = oBState == null ? null : oBState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_PG
     *
     * @return the value of ORDER_MGR.O_PG
     *
     * @mbggenerated
     */
    public String getoPg() {
        return oPg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_PG
     *
     * @param oPg the value for ORDER_MGR.O_PG
     *
     * @mbggenerated
     */
    public void setoPg(String oPg) {
        this.oPg = oPg == null ? null : oPg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_SETTLE
     *
     * @return the value of ORDER_MGR.O_SETTLE
     *
     * @mbggenerated
     */
    public String getoSettle() {
        return oSettle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_SETTLE
     *
     * @param oSettle the value for ORDER_MGR.O_SETTLE
     *
     * @mbggenerated
     */
    public void setoSettle(String oSettle) {
        this.oSettle = oSettle == null ? null : oSettle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_BANK_NAME
     *
     * @return the value of ORDER_MGR.O_BANK_NAME
     *
     * @mbggenerated
     */
    public String getoBankName() {
        return oBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_BANK_NAME
     *
     * @param oBankName the value for ORDER_MGR.O_BANK_NAME
     *
     * @mbggenerated
     */
    public void setoBankName(String oBankName) {
        this.oBankName = oBankName == null ? null : oBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_BANK
     *
     * @return the value of ORDER_MGR.O_BANK
     *
     * @mbggenerated
     */
    public String getoBank() {
        return oBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_BANK
     *
     * @param oBank the value for ORDER_MGR.O_BANK
     *
     * @mbggenerated
     */
    public void setoBank(String oBank) {
        this.oBank = oBank == null ? null : oBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_BANK_ACC
     *
     * @return the value of ORDER_MGR.O_BANK_ACC
     *
     * @mbggenerated
     */
    public String getoBankAcc() {
        return oBankAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_BANK_ACC
     *
     * @param oBankAcc the value for ORDER_MGR.O_BANK_ACC
     *
     * @mbggenerated
     */
    public void setoBankAcc(String oBankAcc) {
        this.oBankAcc = oBankAcc == null ? null : oBankAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_BANK_VALID_DT
     *
     * @return the value of ORDER_MGR.O_BANK_VALID_DT
     *
     * @mbggenerated
     */
    public String getoBankValidDt() {
        return oBankValidDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_BANK_VALID_DT
     *
     * @param oBankValidDt the value for ORDER_MGR.O_BANK_VALID_DT
     *
     * @mbggenerated
     */
    public void setoBankValidDt(String oBankValidDt) {
        this.oBankValidDt = oBankValidDt == null ? null : oBankValidDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DELIVERY_COM
     *
     * @return the value of ORDER_MGR.O_DELIVERY_COM
     *
     * @mbggenerated
     */
    public String getoDeliveryCom() {
        return oDeliveryCom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DELIVERY_COM
     *
     * @param oDeliveryCom the value for ORDER_MGR.O_DELIVERY_COM
     *
     * @mbggenerated
     */
    public void setoDeliveryCom(String oDeliveryCom) {
        this.oDeliveryCom = oDeliveryCom == null ? null : oDeliveryCom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DELIVERY_NUM
     *
     * @return the value of ORDER_MGR.O_DELIVERY_NUM
     *
     * @mbggenerated
     */
    public String getoDeliveryNum() {
        return oDeliveryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DELIVERY_NUM
     *
     * @param oDeliveryNum the value for ORDER_MGR.O_DELIVERY_NUM
     *
     * @mbggenerated
     */
    public void setoDeliveryNum(String oDeliveryNum) {
        this.oDeliveryNum = oDeliveryNum == null ? null : oDeliveryNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DELIVERY_WEIGHT
     *
     * @return the value of ORDER_MGR.O_DELIVERY_WEIGHT
     *
     * @mbggenerated
     */
    public String getoDeliveryWeight() {
        return oDeliveryWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DELIVERY_WEIGHT
     *
     * @param oDeliveryWeight the value for ORDER_MGR.O_DELIVERY_WEIGHT
     *
     * @mbggenerated
     */
    public void setoDeliveryWeight(String oDeliveryWeight) {
        this.oDeliveryWeight = oDeliveryWeight == null ? null : oDeliveryWeight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DELIVERY_SIZE
     *
     * @return the value of ORDER_MGR.O_DELIVERY_SIZE
     *
     * @mbggenerated
     */
    public String getoDeliverySize() {
        return oDeliverySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DELIVERY_SIZE
     *
     * @param oDeliverySize the value for ORDER_MGR.O_DELIVERY_SIZE
     *
     * @mbggenerated
     */
    public void setoDeliverySize(String oDeliverySize) {
        this.oDeliverySize = oDeliverySize == null ? null : oDeliverySize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_POINT
     *
     * @return the value of ORDER_MGR.O_USE_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getoUsePoint() {
        return oUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_POINT
     *
     * @param oUsePoint the value for ORDER_MGR.O_USE_POINT
     *
     * @mbggenerated
     */
    public void setoUsePoint(BigDecimal oUsePoint) {
        this.oUsePoint = oUsePoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_CUR_POINT
     *
     * @return the value of ORDER_MGR.O_USE_CUR_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getoUseCurPoint() {
        return oUseCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_CUR_POINT
     *
     * @param oUseCurPoint the value for ORDER_MGR.O_USE_CUR_POINT
     *
     * @mbggenerated
     */
    public void setoUseCurPoint(BigDecimal oUseCurPoint) {
        this.oUseCurPoint = oUseCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_COUPON_NUM
     *
     * @return the value of ORDER_MGR.O_USE_COUPON_NUM
     *
     * @mbggenerated
     */
    public String getoUseCouponNum() {
        return oUseCouponNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_COUPON_NUM
     *
     * @param oUseCouponNum the value for ORDER_MGR.O_USE_COUPON_NUM
     *
     * @mbggenerated
     */
    public void setoUseCouponNum(String oUseCouponNum) {
        this.oUseCouponNum = oUseCouponNum == null ? null : oUseCouponNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_COUPON
     *
     * @return the value of ORDER_MGR.O_USE_COUPON
     *
     * @mbggenerated
     */
    public BigDecimal getoUseCoupon() {
        return oUseCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_COUPON
     *
     * @param oUseCoupon the value for ORDER_MGR.O_USE_COUPON
     *
     * @mbggenerated
     */
    public void setoUseCoupon(BigDecimal oUseCoupon) {
        this.oUseCoupon = oUseCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_CUR_COUPON
     *
     * @return the value of ORDER_MGR.O_USE_CUR_COUPON
     *
     * @mbggenerated
     */
    public BigDecimal getoUseCurCoupon() {
        return oUseCurCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_CUR_COUPON
     *
     * @param oUseCurCoupon the value for ORDER_MGR.O_USE_CUR_COUPON
     *
     * @mbggenerated
     */
    public void setoUseCurCoupon(BigDecimal oUseCurCoupon) {
        this.oUseCurCoupon = oUseCurCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_QTY
     *
     * @return the value of ORDER_MGR.O_TOT_QTY
     *
     * @mbggenerated
     */
    public Long getoTotQty() {
        return oTotQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_QTY
     *
     * @param oTotQty the value for ORDER_MGR.O_TOT_QTY
     *
     * @mbggenerated
     */
    public void setoTotQty(Long oTotQty) {
        this.oTotQty = oTotQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_PRICE
     *
     * @return the value of ORDER_MGR.O_TOT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotPrice() {
        return oTotPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_PRICE
     *
     * @param oTotPrice the value for ORDER_MGR.O_TOT_PRICE
     *
     * @mbggenerated
     */
    public void setoTotPrice(BigDecimal oTotPrice) {
        this.oTotPrice = oTotPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_CUR_PRICE
     *
     * @return the value of ORDER_MGR.O_TOT_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotCurPrice() {
        return oTotCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_CUR_PRICE
     *
     * @param oTotCurPrice the value for ORDER_MGR.O_TOT_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setoTotCurPrice(BigDecimal oTotCurPrice) {
        this.oTotCurPrice = oTotCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_DELIVERY_PRICE
     *
     * @return the value of ORDER_MGR.O_TOT_DELIVERY_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotDeliveryPrice() {
        return oTotDeliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_DELIVERY_PRICE
     *
     * @param oTotDeliveryPrice the value for ORDER_MGR.O_TOT_DELIVERY_PRICE
     *
     * @mbggenerated
     */
    public void setoTotDeliveryPrice(BigDecimal oTotDeliveryPrice) {
        this.oTotDeliveryPrice = oTotDeliveryPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_DELIVERY_CUR_PRICE
     *
     * @return the value of ORDER_MGR.O_TOT_DELIVERY_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotDeliveryCurPrice() {
        return oTotDeliveryCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_DELIVERY_CUR_PRICE
     *
     * @param oTotDeliveryCurPrice the value for ORDER_MGR.O_TOT_DELIVERY_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setoTotDeliveryCurPrice(BigDecimal oTotDeliveryCurPrice) {
        this.oTotDeliveryCurPrice = oTotDeliveryCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TAX_PRICE
     *
     * @return the value of ORDER_MGR.O_TAX_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTaxPrice() {
        return oTaxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TAX_PRICE
     *
     * @param oTaxPrice the value for ORDER_MGR.O_TAX_PRICE
     *
     * @mbggenerated
     */
    public void setoTaxPrice(BigDecimal oTaxPrice) {
        this.oTaxPrice = oTaxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TAX_CUR_PRICE
     *
     * @return the value of ORDER_MGR.O_TAX_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTaxCurPrice() {
        return oTaxCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TAX_CUR_PRICE
     *
     * @param oTaxCurPrice the value for ORDER_MGR.O_TAX_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setoTaxCurPrice(BigDecimal oTaxCurPrice) {
        this.oTaxCurPrice = oTaxCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_MEM_DISCOUNT_CUR_PRICE
     *
     * @return the value of ORDER_MGR.O_TOT_MEM_DISCOUNT_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotMemDiscountCurPrice() {
        return oTotMemDiscountCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_MEM_DISCOUNT_CUR_PRICE
     *
     * @param oTotMemDiscountCurPrice the value for ORDER_MGR.O_TOT_MEM_DISCOUNT_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setoTotMemDiscountCurPrice(BigDecimal oTotMemDiscountCurPrice) {
        this.oTotMemDiscountCurPrice = oTotMemDiscountCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_MEM_DISCOUNT_PRICE
     *
     * @return the value of ORDER_MGR.O_TOT_MEM_DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotMemDiscountPrice() {
        return oTotMemDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_MEM_DISCOUNT_PRICE
     *
     * @param oTotMemDiscountPrice the value for ORDER_MGR.O_TOT_MEM_DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public void setoTotMemDiscountPrice(BigDecimal oTotMemDiscountPrice) {
        this.oTotMemDiscountPrice = oTotMemDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_SPRICE
     *
     * @return the value of ORDER_MGR.O_TOT_SPRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotSprice() {
        return oTotSprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_SPRICE
     *
     * @param oTotSprice the value for ORDER_MGR.O_TOT_SPRICE
     *
     * @mbggenerated
     */
    public void setoTotSprice(BigDecimal oTotSprice) {
        this.oTotSprice = oTotSprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_CUR_SPRICE
     *
     * @return the value of ORDER_MGR.O_TOT_CUR_SPRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoTotCurSprice() {
        return oTotCurSprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_CUR_SPRICE
     *
     * @param oTotCurSprice the value for ORDER_MGR.O_TOT_CUR_SPRICE
     *
     * @mbggenerated
     */
    public void setoTotCurSprice(BigDecimal oTotCurSprice) {
        this.oTotCurSprice = oTotCurSprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_MEM_POINT
     *
     * @return the value of ORDER_MGR.O_TOT_MEM_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getoTotMemPoint() {
        return oTotMemPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_MEM_POINT
     *
     * @param oTotMemPoint the value for ORDER_MGR.O_TOT_MEM_POINT
     *
     * @mbggenerated
     */
    public void setoTotMemPoint(BigDecimal oTotMemPoint) {
        this.oTotMemPoint = oTotMemPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_MEM_CUR_POINT
     *
     * @return the value of ORDER_MGR.O_TOT_MEM_CUR_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getoTotMemCurPoint() {
        return oTotMemCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_MEM_CUR_POINT
     *
     * @param oTotMemCurPoint the value for ORDER_MGR.O_TOT_MEM_CUR_POINT
     *
     * @mbggenerated
     */
    public void setoTotMemCurPoint(BigDecimal oTotMemCurPoint) {
        this.oTotMemCurPoint = oTotMemCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_POINT
     *
     * @return the value of ORDER_MGR.O_TOT_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getoTotPoint() {
        return oTotPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_POINT
     *
     * @param oTotPoint the value for ORDER_MGR.O_TOT_POINT
     *
     * @mbggenerated
     */
    public void setoTotPoint(BigDecimal oTotPoint) {
        this.oTotPoint = oTotPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_TOT_CUR_POINT
     *
     * @return the value of ORDER_MGR.O_TOT_CUR_POINT
     *
     * @mbggenerated
     */
    public BigDecimal getoTotCurPoint() {
        return oTotCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_TOT_CUR_POINT
     *
     * @param oTotCurPoint the value for ORDER_MGR.O_TOT_CUR_POINT
     *
     * @mbggenerated
     */
    public void setoTotCurPoint(BigDecimal oTotCurPoint) {
        this.oTotCurPoint = oTotCurPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_APPR_NO
     *
     * @return the value of ORDER_MGR.O_APPR_NO
     *
     * @mbggenerated
     */
    public String getoApprNo() {
        return oApprNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_APPR_NO
     *
     * @param oApprNo the value for ORDER_MGR.O_APPR_NO
     *
     * @mbggenerated
     */
    public void setoApprNo(String oApprNo) {
        this.oApprNo = oApprNo == null ? null : oApprNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_APPR_DT
     *
     * @return the value of ORDER_MGR.O_APPR_DT
     *
     * @mbggenerated
     */
    public Date getoApprDt() {
        return oApprDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_APPR_DT
     *
     * @param oApprDt the value for ORDER_MGR.O_APPR_DT
     *
     * @mbggenerated
     */
    public void setoApprDt(Date oApprDt) {
        this.oApprDt = oApprDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_STATUS
     *
     * @return the value of ORDER_MGR.O_STATUS
     *
     * @mbggenerated
     */
    public String getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_STATUS
     *
     * @param oStatus the value for ORDER_MGR.O_STATUS
     *
     * @mbggenerated
     */
    public void setoStatus(String oStatus) {
        this.oStatus = oStatus == null ? null : oStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_ADD_POINT
     *
     * @return the value of ORDER_MGR.O_ADD_POINT
     *
     * @mbggenerated
     */
    public String getoAddPoint() {
        return oAddPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_ADD_POINT
     *
     * @param oAddPoint the value for ORDER_MGR.O_ADD_POINT
     *
     * @mbggenerated
     */
    public void setoAddPoint(String oAddPoint) {
        this.oAddPoint = oAddPoint == null ? null : oAddPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_ESCROW
     *
     * @return the value of ORDER_MGR.O_ESCROW
     *
     * @mbggenerated
     */
    public String getoEscrow() {
        return oEscrow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_ESCROW
     *
     * @param oEscrow the value for ORDER_MGR.O_ESCROW
     *
     * @mbggenerated
     */
    public void setoEscrow(String oEscrow) {
        this.oEscrow = oEscrow == null ? null : oEscrow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_RETURN_BANK
     *
     * @return the value of ORDER_MGR.O_RETURN_BANK
     *
     * @mbggenerated
     */
    public String getoReturnBank() {
        return oReturnBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_RETURN_BANK
     *
     * @param oReturnBank the value for ORDER_MGR.O_RETURN_BANK
     *
     * @mbggenerated
     */
    public void setoReturnBank(String oReturnBank) {
        this.oReturnBank = oReturnBank == null ? null : oReturnBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_RETURN_ACC
     *
     * @return the value of ORDER_MGR.O_RETURN_ACC
     *
     * @mbggenerated
     */
    public String getoReturnAcc() {
        return oReturnAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_RETURN_ACC
     *
     * @param oReturnAcc the value for ORDER_MGR.O_RETURN_ACC
     *
     * @mbggenerated
     */
    public void setoReturnAcc(String oReturnAcc) {
        this.oReturnAcc = oReturnAcc == null ? null : oReturnAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_RETURN_NAME
     *
     * @return the value of ORDER_MGR.O_RETURN_NAME
     *
     * @mbggenerated
     */
    public String getoReturnName() {
        return oReturnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_RETURN_NAME
     *
     * @param oReturnName the value for ORDER_MGR.O_RETURN_NAME
     *
     * @mbggenerated
     */
    public void setoReturnName(String oReturnName) {
        this.oReturnName = oReturnName == null ? null : oReturnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CEL_NO
     *
     * @return the value of ORDER_MGR.O_CEL_NO
     *
     * @mbggenerated
     */
    public String getoCelNo() {
        return oCelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CEL_NO
     *
     * @param oCelNo the value for ORDER_MGR.O_CEL_NO
     *
     * @mbggenerated
     */
    public void setoCelNo(String oCelNo) {
        this.oCelNo = oCelNo == null ? null : oCelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CEL_REQ_DT
     *
     * @return the value of ORDER_MGR.O_CEL_REQ_DT
     *
     * @mbggenerated
     */
    public Date getoCelReqDt() {
        return oCelReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CEL_REQ_DT
     *
     * @param oCelReqDt the value for ORDER_MGR.O_CEL_REQ_DT
     *
     * @mbggenerated
     */
    public void setoCelReqDt(Date oCelReqDt) {
        this.oCelReqDt = oCelReqDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CEL_REG_DT
     *
     * @return the value of ORDER_MGR.O_CEL_REG_DT
     *
     * @mbggenerated
     */
    public Date getoCelRegDt() {
        return oCelRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CEL_REG_DT
     *
     * @param oCelRegDt the value for ORDER_MGR.O_CEL_REG_DT
     *
     * @mbggenerated
     */
    public void setoCelRegDt(Date oCelRegDt) {
        this.oCelRegDt = oCelRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CEL_MEMO
     *
     * @return the value of ORDER_MGR.O_CEL_MEMO
     *
     * @mbggenerated
     */
    public String getoCelMemo() {
        return oCelMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CEL_MEMO
     *
     * @param oCelMemo the value for ORDER_MGR.O_CEL_MEMO
     *
     * @mbggenerated
     */
    public void setoCelMemo(String oCelMemo) {
        this.oCelMemo = oCelMemo == null ? null : oCelMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CEL_STATUS
     *
     * @return the value of ORDER_MGR.O_CEL_STATUS
     *
     * @mbggenerated
     */
    public String getoCelStatus() {
        return oCelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CEL_STATUS
     *
     * @param oCelStatus the value for ORDER_MGR.O_CEL_STATUS
     *
     * @mbggenerated
     */
    public void setoCelStatus(String oCelStatus) {
        this.oCelStatus = oCelStatus == null ? null : oCelStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_LNG
     *
     * @return the value of ORDER_MGR.O_USE_LNG
     *
     * @mbggenerated
     */
    public String getoUseLng() {
        return oUseLng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_LNG
     *
     * @param oUseLng the value for ORDER_MGR.O_USE_LNG
     *
     * @mbggenerated
     */
    public void setoUseLng(String oUseLng) {
        this.oUseLng = oUseLng == null ? null : oUseLng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_CUR
     *
     * @return the value of ORDER_MGR.O_USE_CUR
     *
     * @mbggenerated
     */
    public String getoUseCur() {
        return oUseCur;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_CUR
     *
     * @param oUseCur the value for ORDER_MGR.O_USE_CUR
     *
     * @mbggenerated
     */
    public void setoUseCur(String oUseCur) {
        this.oUseCur = oUseCur == null ? null : oUseCur.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_CUR_RATE
     *
     * @return the value of ORDER_MGR.O_USE_CUR_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getoUseCurRate() {
        return oUseCurRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_CUR_RATE
     *
     * @param oUseCurRate the value for ORDER_MGR.O_USE_CUR_RATE
     *
     * @mbggenerated
     */
    public void setoUseCurRate(BigDecimal oUseCurRate) {
        this.oUseCurRate = oUseCurRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_USE_CUR_ORG_RATE
     *
     * @return the value of ORDER_MGR.O_USE_CUR_ORG_RATE
     *
     * @mbggenerated
     */
    public BigDecimal getoUseCurOrgRate() {
        return oUseCurOrgRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_USE_CUR_ORG_RATE
     *
     * @param oUseCurOrgRate the value for ORDER_MGR.O_USE_CUR_ORG_RATE
     *
     * @mbggenerated
     */
    public void setoUseCurOrgRate(BigDecimal oUseCurOrgRate) {
        this.oUseCurOrgRate = oUseCurOrgRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_FOREIGN_PG_KEY
     *
     * @return the value of ORDER_MGR.O_FOREIGN_PG_KEY
     *
     * @mbggenerated
     */
    public String getoForeignPgKey() {
        return oForeignPgKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_FOREIGN_PG_KEY
     *
     * @param oForeignPgKey the value for ORDER_MGR.O_FOREIGN_PG_KEY
     *
     * @mbggenerated
     */
    public void setoForeignPgKey(String oForeignPgKey) {
        this.oForeignPgKey = oForeignPgKey == null ? null : oForeignPgKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_FOREIGN_PG_ID
     *
     * @return the value of ORDER_MGR.O_FOREIGN_PG_ID
     *
     * @mbggenerated
     */
    public String getoForeignPgId() {
        return oForeignPgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_FOREIGN_PG_ID
     *
     * @param oForeignPgId the value for ORDER_MGR.O_FOREIGN_PG_ID
     *
     * @mbggenerated
     */
    public void setoForeignPgId(String oForeignPgId) {
        this.oForeignPgId = oForeignPgId == null ? null : oForeignPgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_ACC
     *
     * @return the value of ORDER_MGR.O_ACC
     *
     * @mbggenerated
     */
    public String getoAcc() {
        return oAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_ACC
     *
     * @param oAcc the value for ORDER_MGR.O_ACC
     *
     * @mbggenerated
     */
    public void setoAcc(String oAcc) {
        this.oAcc = oAcc == null ? null : oAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CASH_YN
     *
     * @return the value of ORDER_MGR.O_CASH_YN
     *
     * @mbggenerated
     */
    public String getoCashYn() {
        return oCashYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CASH_YN
     *
     * @param oCashYn the value for ORDER_MGR.O_CASH_YN
     *
     * @mbggenerated
     */
    public void setoCashYn(String oCashYn) {
        this.oCashYn = oCashYn == null ? null : oCashYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CASH_AUTH_NO
     *
     * @return the value of ORDER_MGR.O_CASH_AUTH_NO
     *
     * @mbggenerated
     */
    public String getoCashAuthNo() {
        return oCashAuthNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CASH_AUTH_NO
     *
     * @param oCashAuthNo the value for ORDER_MGR.O_CASH_AUTH_NO
     *
     * @mbggenerated
     */
    public void setoCashAuthNo(String oCashAuthNo) {
        this.oCashAuthNo = oCashAuthNo == null ? null : oCashAuthNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_CASH_INFO
     *
     * @return the value of ORDER_MGR.O_CASH_INFO
     *
     * @mbggenerated
     */
    public String getoCashInfo() {
        return oCashInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_CASH_INFO
     *
     * @param oCashInfo the value for ORDER_MGR.O_CASH_INFO
     *
     * @mbggenerated
     */
    public void setoCashInfo(String oCashInfo) {
        this.oCashInfo = oCashInfo == null ? null : oCashInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_SELF_WRITE
     *
     * @return the value of ORDER_MGR.O_SELF_WRITE
     *
     * @mbggenerated
     */
    public String getoSelfWrite() {
        return oSelfWrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_SELF_WRITE
     *
     * @param oSelfWrite the value for ORDER_MGR.O_SELF_WRITE
     *
     * @mbggenerated
     */
    public void setoSelfWrite(String oSelfWrite) {
        this.oSelfWrite = oSelfWrite == null ? null : oSelfWrite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_FIRST_YN
     *
     * @return the value of ORDER_MGR.O_FIRST_YN
     *
     * @mbggenerated
     */
    public String getoFirstYn() {
        return oFirstYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_FIRST_YN
     *
     * @param oFirstYn the value for ORDER_MGR.O_FIRST_YN
     *
     * @mbggenerated
     */
    public void setoFirstYn(String oFirstYn) {
        this.oFirstYn = oFirstYn == null ? null : oFirstYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_PATH
     *
     * @return the value of ORDER_MGR.O_PATH
     *
     * @mbggenerated
     */
    public String getoPath() {
        return oPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_PATH
     *
     * @param oPath the value for ORDER_MGR.O_PATH
     *
     * @mbggenerated
     */
    public void setoPath(String oPath) {
        this.oPath = oPath == null ? null : oPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DISCOUNT_RATE
     *
     * @return the value of ORDER_MGR.O_DISCOUNT_RATE
     *
     * @mbggenerated
     */
    public Byte getoDiscountRate() {
        return oDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DISCOUNT_RATE
     *
     * @param oDiscountRate the value for ORDER_MGR.O_DISCOUNT_RATE
     *
     * @mbggenerated
     */
    public void setoDiscountRate(Byte oDiscountRate) {
        this.oDiscountRate = oDiscountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DISCOUNT_PRICE
     *
     * @return the value of ORDER_MGR.O_DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoDiscountPrice() {
        return oDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DISCOUNT_PRICE
     *
     * @param oDiscountPrice the value for ORDER_MGR.O_DISCOUNT_PRICE
     *
     * @mbggenerated
     */
    public void setoDiscountPrice(BigDecimal oDiscountPrice) {
        this.oDiscountPrice = oDiscountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_DISCOUNT_CUR_PRICE
     *
     * @return the value of ORDER_MGR.O_DISCOUNT_CUR_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getoDiscountCurPrice() {
        return oDiscountCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_DISCOUNT_CUR_PRICE
     *
     * @param oDiscountCurPrice the value for ORDER_MGR.O_DISCOUNT_CUR_PRICE
     *
     * @mbggenerated
     */
    public void setoDiscountCurPrice(BigDecimal oDiscountCurPrice) {
        this.oDiscountCurPrice = oDiscountCurPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_SHIPPING_NO
     *
     * @return the value of ORDER_MGR.O_SHIPPING_NO
     *
     * @mbggenerated
     */
    public String getoShippingNo() {
        return oShippingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_SHIPPING_NO
     *
     * @param oShippingNo the value for ORDER_MGR.O_SHIPPING_NO
     *
     * @mbggenerated
     */
    public void setoShippingNo(String oShippingNo) {
        this.oShippingNo = oShippingNo == null ? null : oShippingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_WECHAT_TMP
     *
     * @return the value of ORDER_MGR.O_WECHAT_TMP
     *
     * @mbggenerated
     */
    public String getoWechatTmp() {
        return oWechatTmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_WECHAT_TMP
     *
     * @param oWechatTmp the value for ORDER_MGR.O_WECHAT_TMP
     *
     * @mbggenerated
     */
    public void setoWechatTmp(String oWechatTmp) {
        this.oWechatTmp = oWechatTmp == null ? null : oWechatTmp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_REG_IP
     *
     * @return the value of ORDER_MGR.O_REG_IP
     *
     * @mbggenerated
     */
    public String getoRegIp() {
        return oRegIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_REG_IP
     *
     * @param oRegIp the value for ORDER_MGR.O_REG_IP
     *
     * @mbggenerated
     */
    public void setoRegIp(String oRegIp) {
        this.oRegIp = oRegIp == null ? null : oRegIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_REG_DT
     *
     * @return the value of ORDER_MGR.O_REG_DT
     *
     * @mbggenerated
     */
    public Date getoRegDt() {
        return oRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_REG_DT
     *
     * @param oRegDt the value for ORDER_MGR.O_REG_DT
     *
     * @mbggenerated
     */
    public void setoRegDt(Date oRegDt) {
        this.oRegDt = oRegDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_MGR.O_B_MEMO
     *
     * @return the value of ORDER_MGR.O_B_MEMO
     *
     * @mbggenerated
     */
    public String getoBMemo() {
        return oBMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_MGR.O_B_MEMO
     *
     * @param oBMemo the value for ORDER_MGR.O_B_MEMO
     *
     * @mbggenerated
     */
    public void setoBMemo(String oBMemo) {
        this.oBMemo = oBMemo == null ? null : oBMemo.trim();
    }
}