package com.atlsmall.entity;

import java.util.ArrayList;
import java.util.List;

public class ProductImgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public ProductImgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPmNoIsNull() {
            addCriterion("PM_NO is null");
            return (Criteria) this;
        }

        public Criteria andPmNoIsNotNull() {
            addCriterion("PM_NO is not null");
            return (Criteria) this;
        }

        public Criteria andPmNoEqualTo(Long value) {
            addCriterion("PM_NO =", value, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoNotEqualTo(Long value) {
            addCriterion("PM_NO <>", value, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoGreaterThan(Long value) {
            addCriterion("PM_NO >", value, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoGreaterThanOrEqualTo(Long value) {
            addCriterion("PM_NO >=", value, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoLessThan(Long value) {
            addCriterion("PM_NO <", value, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoLessThanOrEqualTo(Long value) {
            addCriterion("PM_NO <=", value, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoIn(List<Long> values) {
            addCriterion("PM_NO in", values, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoNotIn(List<Long> values) {
            addCriterion("PM_NO not in", values, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoBetween(Long value1, Long value2) {
            addCriterion("PM_NO between", value1, value2, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPmNoNotBetween(Long value1, Long value2) {
            addCriterion("PM_NO not between", value1, value2, "pmNo");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNull() {
            addCriterion("P_CODE is null");
            return (Criteria) this;
        }

        public Criteria andPCodeIsNotNull() {
            addCriterion("P_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andPCodeEqualTo(String value) {
            addCriterion("P_CODE =", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotEqualTo(String value) {
            addCriterion("P_CODE <>", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThan(String value) {
            addCriterion("P_CODE >", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeGreaterThanOrEqualTo(String value) {
            addCriterion("P_CODE >=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThan(String value) {
            addCriterion("P_CODE <", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLessThanOrEqualTo(String value) {
            addCriterion("P_CODE <=", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeLike(String value) {
            addCriterion("P_CODE like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotLike(String value) {
            addCriterion("P_CODE not like", value, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeIn(List<String> values) {
            addCriterion("P_CODE in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotIn(List<String> values) {
            addCriterion("P_CODE not in", values, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeBetween(String value1, String value2) {
            addCriterion("P_CODE between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPCodeNotBetween(String value1, String value2) {
            addCriterion("P_CODE not between", value1, value2, "pCode");
            return (Criteria) this;
        }

        public Criteria andPmTypeIsNull() {
            addCriterion("PM_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPmTypeIsNotNull() {
            addCriterion("PM_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPmTypeEqualTo(String value) {
            addCriterion("PM_TYPE =", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeNotEqualTo(String value) {
            addCriterion("PM_TYPE <>", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeGreaterThan(String value) {
            addCriterion("PM_TYPE >", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PM_TYPE >=", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeLessThan(String value) {
            addCriterion("PM_TYPE <", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeLessThanOrEqualTo(String value) {
            addCriterion("PM_TYPE <=", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeLike(String value) {
            addCriterion("PM_TYPE like", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeNotLike(String value) {
            addCriterion("PM_TYPE not like", value, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeIn(List<String> values) {
            addCriterion("PM_TYPE in", values, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeNotIn(List<String> values) {
            addCriterion("PM_TYPE not in", values, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeBetween(String value1, String value2) {
            addCriterion("PM_TYPE between", value1, value2, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmTypeNotBetween(String value1, String value2) {
            addCriterion("PM_TYPE not between", value1, value2, "pmType");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameIsNull() {
            addCriterion("PM_SAVE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameIsNotNull() {
            addCriterion("PM_SAVE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameEqualTo(String value) {
            addCriterion("PM_SAVE_NAME =", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameNotEqualTo(String value) {
            addCriterion("PM_SAVE_NAME <>", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameGreaterThan(String value) {
            addCriterion("PM_SAVE_NAME >", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameGreaterThanOrEqualTo(String value) {
            addCriterion("PM_SAVE_NAME >=", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameLessThan(String value) {
            addCriterion("PM_SAVE_NAME <", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameLessThanOrEqualTo(String value) {
            addCriterion("PM_SAVE_NAME <=", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameLike(String value) {
            addCriterion("PM_SAVE_NAME like", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameNotLike(String value) {
            addCriterion("PM_SAVE_NAME not like", value, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameIn(List<String> values) {
            addCriterion("PM_SAVE_NAME in", values, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameNotIn(List<String> values) {
            addCriterion("PM_SAVE_NAME not in", values, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameBetween(String value1, String value2) {
            addCriterion("PM_SAVE_NAME between", value1, value2, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmSaveNameNotBetween(String value1, String value2) {
            addCriterion("PM_SAVE_NAME not between", value1, value2, "pmSaveName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameIsNull() {
            addCriterion("PM_REAL_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPmRealNameIsNotNull() {
            addCriterion("PM_REAL_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPmRealNameEqualTo(String value) {
            addCriterion("PM_REAL_NAME =", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameNotEqualTo(String value) {
            addCriterion("PM_REAL_NAME <>", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameGreaterThan(String value) {
            addCriterion("PM_REAL_NAME >", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("PM_REAL_NAME >=", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameLessThan(String value) {
            addCriterion("PM_REAL_NAME <", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameLessThanOrEqualTo(String value) {
            addCriterion("PM_REAL_NAME <=", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameLike(String value) {
            addCriterion("PM_REAL_NAME like", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameNotLike(String value) {
            addCriterion("PM_REAL_NAME not like", value, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameIn(List<String> values) {
            addCriterion("PM_REAL_NAME in", values, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameNotIn(List<String> values) {
            addCriterion("PM_REAL_NAME not in", values, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameBetween(String value1, String value2) {
            addCriterion("PM_REAL_NAME between", value1, value2, "pmRealName");
            return (Criteria) this;
        }

        public Criteria andPmRealNameNotBetween(String value1, String value2) {
            addCriterion("PM_REAL_NAME not between", value1, value2, "pmRealName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}