package com.atlsmall.entity;

public class ProductImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMG.PM_NO
     *
     * @mbggenerated
     */
    private Long pmNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMG.P_CODE
     *
     * @mbggenerated
     */
    private String pCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMG.PM_TYPE
     *
     * @mbggenerated
     */
    private String pmType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMG.PM_SAVE_NAME
     *
     * @mbggenerated
     */
    private String pmSaveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMG.PM_REAL_NAME
     *
     * @mbggenerated
     */
    private String pmRealName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMG.PM_NO
     *
     * @return the value of PRODUCT_IMG.PM_NO
     *
     * @mbggenerated
     */
    public Long getPmNo() {
        return pmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMG.PM_NO
     *
     * @param pmNo the value for PRODUCT_IMG.PM_NO
     *
     * @mbggenerated
     */
    public void setPmNo(Long pmNo) {
        this.pmNo = pmNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMG.P_CODE
     *
     * @return the value of PRODUCT_IMG.P_CODE
     *
     * @mbggenerated
     */
    public String getpCode() {
        return pCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMG.P_CODE
     *
     * @param pCode the value for PRODUCT_IMG.P_CODE
     *
     * @mbggenerated
     */
    public void setpCode(String pCode) {
        this.pCode = pCode == null ? null : pCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMG.PM_TYPE
     *
     * @return the value of PRODUCT_IMG.PM_TYPE
     *
     * @mbggenerated
     */
    public String getPmType() {
        return pmType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMG.PM_TYPE
     *
     * @param pmType the value for PRODUCT_IMG.PM_TYPE
     *
     * @mbggenerated
     */
    public void setPmType(String pmType) {
        this.pmType = pmType == null ? null : pmType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMG.PM_SAVE_NAME
     *
     * @return the value of PRODUCT_IMG.PM_SAVE_NAME
     *
     * @mbggenerated
     */
    public String getPmSaveName() {
        return pmSaveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMG.PM_SAVE_NAME
     *
     * @param pmSaveName the value for PRODUCT_IMG.PM_SAVE_NAME
     *
     * @mbggenerated
     */
    public void setPmSaveName(String pmSaveName) {
        this.pmSaveName = pmSaveName == null ? null : pmSaveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMG.PM_REAL_NAME
     *
     * @return the value of PRODUCT_IMG.PM_REAL_NAME
     *
     * @mbggenerated
     */
    public String getPmRealName() {
        return pmRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMG.PM_REAL_NAME
     *
     * @param pmRealName the value for PRODUCT_IMG.PM_REAL_NAME
     *
     * @mbggenerated
     */
    public void setPmRealName(String pmRealName) {
        this.pmRealName = pmRealName == null ? null : pmRealName.trim();
    }
}