package com.atlsmall.dao;

import com.atlsmall.entity.CommCode;
import com.atlsmall.entity.CommCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int countByExample(CommCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int deleteByExample(CommCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ccNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int insert(CommCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int insertSelective(CommCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    List<CommCode> selectByExample(CommCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    CommCode selectByPrimaryKey(Integer ccNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommCode record, @Param("example") CommCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommCode record, @Param("example") CommCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_CODE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommCode record);
}