package com.atlsmall.dao;

import com.atlsmall.entity.OrderMgr;
import com.atlsmall.entity.OrderMgrExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMgrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int countByExample(OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int deleteByExample(OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long oNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int insert(OrderMgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int insertSelective(OrderMgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    List<OrderMgr> selectByExampleWithBLOBs(OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    List<OrderMgr> selectByExample(OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    OrderMgr selectByPrimaryKey(Long oNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderMgr record, @Param("example") OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") OrderMgr record, @Param("example") OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderMgr record, @Param("example") OrderMgrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderMgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(OrderMgr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_MGR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderMgr record);
}