package com.atlsmall.dao;

import com.atlsmall.entity.ProductImg;
import com.atlsmall.entity.ProductImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int countByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int deleteByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long pmNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int insert(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int insertSelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    List<ProductImg> selectByExample(ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    ProductImg selectByPrimaryKey(Long pmNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductImg record, @Param("example") ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductImg record, @Param("example") ProductImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductImg record);
}